// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "text", "symbols": ["sentence"]},
    {"name": "sentence$subexpression$1", "symbols": ["copula_base_sA", "copula_tail_sA"]},
    {"name": "sentence$subexpression$1", "symbols": ["copula_base_pA", "copula_tail_pA"]},
    {"name": "sentence$subexpression$1", "symbols": ["copula_base_sI", "copula_tail_sI"]},
    {"name": "sentence$subexpression$1", "symbols": ["copula_base_pI", "copula_tail_pI"]},
    {"name": "sentence$subexpression$1", "symbols": ["negative_copula_base", "copula_tail_x"]},
    {"name": "sentence$subexpression$1", "symbols": ["verb_2o_base", "verb_2o_tail"]},
    {"name": "sentence$ebnf$1$subexpression$1", "symbols": ["_", "prepositional_phrase"]},
    {"name": "sentence$ebnf$1", "symbols": ["sentence$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "sentence$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "sentence", "symbols": ["sentence$subexpression$1", "sentence$ebnf$1"]},
    {"name": "fragment", "symbols": ["noun_phrase_sA"]},
    {"name": "fragment", "symbols": ["noun_phrase_sI"]},
    {"name": "fragment", "symbols": ["noun_phrase_pA"]},
    {"name": "fragment", "symbols": ["noun_phrase_pI"]},
    {"name": "copula_base", "symbols": ["copula_base_sA"]},
    {"name": "copula_base", "symbols": ["copula_base_pA"]},
    {"name": "copula_base", "symbols": ["copula_base_sI"]},
    {"name": "copula_base", "symbols": ["copula_base_sA"]},
    {"name": "negative_copula_base", "symbols": ["negative_copula_base_sA"]},
    {"name": "negative_copula_base", "symbols": ["negative_copula_base_pA"]},
    {"name": "negative_copula_base", "symbols": ["negative_copula_base_sI"]},
    {"name": "negative_copula_base", "symbols": ["negative_copula_base_pI"]},
    {"name": "copula_base_sA", "symbols": ["1s_copula_base"]},
    {"name": "copula_base_sA", "symbols": ["2s_copula_base"]},
    {"name": "copula_base_sA", "symbols": ["3sA_copula_base"]},
    {"name": "copula_base_pA", "symbols": ["1p_copula_base"]},
    {"name": "copula_base_pA", "symbols": ["2p_copula_base"]},
    {"name": "copula_base_pA", "symbols": ["3pA_copula_base"]},
    {"name": "copula_base_sI", "symbols": ["3sI_copula_base"]},
    {"name": "copula_base_pI", "symbols": ["3pI_copula_base"]},
    {"name": "negative_copula_base_sA", "symbols": ["1s_negative_copula_base"]},
    {"name": "negative_copula_base_sA", "symbols": ["2s_negative_copula_base"]},
    {"name": "negative_copula_base_sA", "symbols": ["3sA_negative_copula_base"]},
    {"name": "negative_copula_base_pA", "symbols": ["1p_negative_copula_base"]},
    {"name": "negative_copula_base_pA", "symbols": ["2p_negative_copula_base"]},
    {"name": "negative_copula_base_pA", "symbols": ["3pA_negative_copula_base"]},
    {"name": "negative_copula_base_sI", "symbols": ["3sI_negative_copula_base"]},
    {"name": "negative_copula_base_pI", "symbols": ["3pI_negative_copula_base"]},
    {"name": "1s_copula_base", "symbols": ["1ss", "_", "1s_copula"]},
    {"name": "1p_copula_base", "symbols": ["1ps", "_", "1p_copula"]},
    {"name": "2s_copula_base", "symbols": ["2ss", "_", "2s_copula"]},
    {"name": "2p_copula_base", "symbols": ["2ps", "_", "2p_copula"]},
    {"name": "3sA_copula_base$subexpression$1", "symbols": ["demonstrative_s"]},
    {"name": "3sA_copula_base$subexpression$1", "symbols": ["3ssF"]},
    {"name": "3sA_copula_base$subexpression$1", "symbols": ["3ssM"]},
    {"name": "3sA_copula_base$subexpression$1", "symbols": ["3ssI"]},
    {"name": "3sA_copula_base$subexpression$1", "symbols": ["noun_phrase_sA"]},
    {"name": "3sA_copula_base", "symbols": ["3sA_copula_base$subexpression$1", "_", "3s_copula"]},
    {"name": "3sA_copula_base", "symbols": ["3ssN", "_", "3p_copula"]},
    {"name": "3pA_copula_base$subexpression$1", "symbols": ["demonstrative_p"]},
    {"name": "3pA_copula_base$subexpression$1", "symbols": ["3ps"]},
    {"name": "3pA_copula_base$subexpression$1", "symbols": ["noun_phrase_pA"]},
    {"name": "3pA_copula_base", "symbols": ["3pA_copula_base$subexpression$1", "_", "3p_copula"]},
    {"name": "3sI_copula_base$subexpression$1", "symbols": ["demonstrative_s"]},
    {"name": "3sI_copula_base$subexpression$1", "symbols": ["3ssI"]},
    {"name": "3sI_copula_base$subexpression$1", "symbols": ["noun_phrase_sI"]},
    {"name": "3sI_copula_base", "symbols": ["3sI_copula_base$subexpression$1", "_", "3s_copula"]},
    {"name": "3pI_copula_base$subexpression$1", "symbols": ["demonstrative_p"]},
    {"name": "3pI_copula_base$subexpression$1", "symbols": ["3ps"]},
    {"name": "3pI_copula_base$subexpression$1", "symbols": ["noun_phrase_pI"]},
    {"name": "3pI_copula_base", "symbols": ["3pI_copula_base$subexpression$1", "_", "3p_copula"]},
    {"name": "1s_negative_copula_base", "symbols": ["1ss", "_", "1s_negative_copula"]},
    {"name": "1p_negative_copula_base", "symbols": ["1ps", "_", "1p_negative_copula"]},
    {"name": "2s_negative_copula_base", "symbols": ["2ss", "_", "2s_negative_copula"]},
    {"name": "2p_negative_copula_base", "symbols": ["2ps", "_", "2p_negative_copula"]},
    {"name": "3sA_negative_copula_base$subexpression$1", "symbols": ["demonstrative_s"]},
    {"name": "3sA_negative_copula_base$subexpression$1", "symbols": ["3ssF"]},
    {"name": "3sA_negative_copula_base$subexpression$1", "symbols": ["3ssM"]},
    {"name": "3sA_negative_copula_base$subexpression$1", "symbols": ["3ssI"]},
    {"name": "3sA_negative_copula_base$subexpression$1", "symbols": ["noun_phrase_sA"]},
    {"name": "3sA_negative_copula_base", "symbols": ["3sA_negative_copula_base$subexpression$1", "_", "3s_negative_copula"]},
    {"name": "3sA_negative_copula_base", "symbols": ["3ssN", "_", "3p_negative_copula"]},
    {"name": "3pA_negative_copula_base$subexpression$1", "symbols": ["demonstrative_p"]},
    {"name": "3pA_negative_copula_base$subexpression$1", "symbols": ["3ps"]},
    {"name": "3pA_negative_copula_base$subexpression$1", "symbols": ["noun_phrase_pA"]},
    {"name": "3pA_negative_copula_base", "symbols": ["3pA_negative_copula_base$subexpression$1", "_", "3p_negative_copula"]},
    {"name": "3sI_negative_copula_base$subexpression$1", "symbols": ["demonstrative_s"]},
    {"name": "3sI_negative_copula_base$subexpression$1", "symbols": ["3ssI"]},
    {"name": "3sI_negative_copula_base$subexpression$1", "symbols": ["noun_phrase_sI"]},
    {"name": "3sI_negative_copula_base", "symbols": ["3sI_negative_copula_base$subexpression$1", "_", "3s_negative_copula"]},
    {"name": "3pI_negative_copula_base$subexpression$1", "symbols": ["demonstrative_p"]},
    {"name": "3pI_negative_copula_base$subexpression$1", "symbols": ["3ps"]},
    {"name": "3pI_negative_copula_base$subexpression$1", "symbols": ["noun_phrase_pI"]},
    {"name": "3pI_negative_copula_base", "symbols": ["3pI_negative_copula_base$subexpression$1", "_", "3p_negative_copula"]},
    {"name": "verb_2o_base", "symbols": ["1s_verb_2o_base"]},
    {"name": "verb_2o_base", "symbols": ["1p_verb_2o_base"]},
    {"name": "verb_2o_base", "symbols": ["2s_verb_2o_base"]},
    {"name": "verb_2o_base", "symbols": ["2p_verb_2o_base"]},
    {"name": "verb_2o_base", "symbols": ["3sA_verb_2o_base"]},
    {"name": "verb_2o_base", "symbols": ["3pA_verb_2o_base"]},
    {"name": "verb_2o_base", "symbols": ["3sI_verb_2o_base"]},
    {"name": "verb_2o_base", "symbols": ["3pI_verb_2o_base"]},
    {"name": "verb_2o_base", "symbols": ["1s_negative_verb_2o_base"]},
    {"name": "verb_2o_base", "symbols": ["1p_negative_verb_2o_base"]},
    {"name": "verb_2o_base", "symbols": ["2s_negative_verb_2o_base"]},
    {"name": "verb_2o_base", "symbols": ["2p_negative_verb_2o_base"]},
    {"name": "verb_2o_base", "symbols": ["3sA_negative_verb_2o_base"]},
    {"name": "verb_2o_base", "symbols": ["3pA_negative_verb_2o_base"]},
    {"name": "verb_2o_base", "symbols": ["3sI_negative_verb_2o_base"]},
    {"name": "verb_2o_base", "symbols": ["3pI_negative_verb_2o_base"]},
    {"name": "1s_verb_2o_base", "symbols": ["1ss", "_", "verb_2o_1s"]},
    {"name": "1p_verb_2o_base", "symbols": ["1ps", "_", "verb_2o_1p"]},
    {"name": "2s_verb_2o_base", "symbols": ["2ss", "_", "verb_2o_2s"]},
    {"name": "2p_verb_2o_base", "symbols": ["2ps", "_", "verb_2o_2p"]},
    {"name": "3sA_verb_2o_base$subexpression$1", "symbols": ["demonstrative_s"]},
    {"name": "3sA_verb_2o_base$subexpression$1", "symbols": ["3ssF"]},
    {"name": "3sA_verb_2o_base$subexpression$1", "symbols": ["3ssM"]},
    {"name": "3sA_verb_2o_base$subexpression$1", "symbols": ["3ssI"]},
    {"name": "3sA_verb_2o_base$subexpression$1", "symbols": ["noun_phrase_sA"]},
    {"name": "3sA_verb_2o_base", "symbols": ["3sA_verb_2o_base$subexpression$1", "_", "verb_2o_3s"]},
    {"name": "3sA_verb_2o_base", "symbols": ["3ssN", "_", "verb_2o_3s"]},
    {"name": "3pA_verb_2o_base$subexpression$1", "symbols": ["demonstrative_p"]},
    {"name": "3pA_verb_2o_base$subexpression$1", "symbols": ["3ps"]},
    {"name": "3pA_verb_2o_base$subexpression$1", "symbols": ["noun_phrase_pA"]},
    {"name": "3pA_verb_2o_base", "symbols": ["3pA_verb_2o_base$subexpression$1", "_", "verb_2o_3p"]},
    {"name": "3sI_verb_2o_base$subexpression$1", "symbols": ["demonstrative_s"]},
    {"name": "3sI_verb_2o_base$subexpression$1", "symbols": ["3ssI"]},
    {"name": "3sI_verb_2o_base$subexpression$1", "symbols": ["noun_phrase_sI"]},
    {"name": "3sI_verb_2o_base", "symbols": ["3sI_verb_2o_base$subexpression$1", "_", "verb_2o_3sI"]},
    {"name": "3pI_verb_2o_base$subexpression$1", "symbols": ["demonstrative_p"]},
    {"name": "3pI_verb_2o_base$subexpression$1", "symbols": ["3ps"]},
    {"name": "3pI_verb_2o_base$subexpression$1", "symbols": ["noun_phrase_pI"]},
    {"name": "3pI_verb_2o_base", "symbols": ["3pI_verb_2o_base$subexpression$1", "_", "verb_2o_3pI"]},
    {"name": "1s_negative_verb_2o_base", "symbols": ["1ss", "_", "negative_verb_2o_1s"]},
    {"name": "1p_negative_verb_2o_base", "symbols": ["1ps", "_", "negative_verb_2o_1p"]},
    {"name": "2s_negative_verb_2o_base", "symbols": ["2ss", "_", "negative_verb_2o_2s"]},
    {"name": "2p_negative_verb_2o_base", "symbols": ["2ps", "_", "negative_verb_2o_2p"]},
    {"name": "3sA_negative_verb_2o_base$subexpression$1", "symbols": ["demonstrative_s"]},
    {"name": "3sA_negative_verb_2o_base$subexpression$1", "symbols": ["3ssF"]},
    {"name": "3sA_negative_verb_2o_base$subexpression$1", "symbols": ["3ssM"]},
    {"name": "3sA_negative_verb_2o_base$subexpression$1", "symbols": ["3ssI"]},
    {"name": "3sA_negative_verb_2o_base$subexpression$1", "symbols": ["noun_phrase_sA"]},
    {"name": "3sA_negative_verb_2o_base", "symbols": ["3sA_negative_verb_2o_base$subexpression$1", "_", "negative_verb_2o_3s"]},
    {"name": "3sA_negative_verb_2o_base", "symbols": ["3ssN", "_", "negative_verb_2o_3p"]},
    {"name": "3pA_negative_verb_2o_base$subexpression$1", "symbols": ["demonstrative_p"]},
    {"name": "3pA_negative_verb_2o_base$subexpression$1", "symbols": ["3ps"]},
    {"name": "3pA_negative_verb_2o_base$subexpression$1", "symbols": ["noun_phrase_pA"]},
    {"name": "3pA_negative_verb_2o_base", "symbols": ["3pA_negative_verb_2o_base$subexpression$1", "_", "negative_verb_2o_3p"]},
    {"name": "3sI_negative_verb_2o_base$subexpression$1", "symbols": ["demonstrative_s"]},
    {"name": "3sI_negative_verb_2o_base$subexpression$1", "symbols": ["3ssI"]},
    {"name": "3sI_negative_verb_2o_base$subexpression$1", "symbols": ["noun_phrase_sI"]},
    {"name": "3sI_negative_verb_2o_base", "symbols": ["3sI_negative_verb_2o_base$subexpression$1", "_", "negative_verb_2o_3sI"]},
    {"name": "3pI_negative_verb_2o_base$subexpression$1", "symbols": ["demonstrative_p"]},
    {"name": "3pI_negative_verb_2o_base$subexpression$1", "symbols": ["3ps"]},
    {"name": "3pI_negative_verb_2o_base$subexpression$1", "symbols": ["noun_phrase_pI"]},
    {"name": "3pI_negative_verb_2o_base", "symbols": ["3pI_negative_verb_2o_base$subexpression$1", "_", "negative_verb_2o_3pI"]},
    {"name": "copula_tail", "symbols": ["copula_tail_p"]},
    {"name": "copula_tail", "symbols": ["copula_tail_s"]},
    {"name": "copula_tail_s", "symbols": ["copula_tail_sA"]},
    {"name": "copula_tail_s", "symbols": ["copula_tail_sI"]},
    {"name": "copula_tail_p", "symbols": ["copula_tail_pA"]},
    {"name": "copula_tail_p", "symbols": ["copula_tail_pI"]},
    {"name": "copula_tail_x$subexpression$1", "symbols": ["adjective_phrase"]},
    {"name": "copula_tail_x$subexpression$1", "symbols": ["adjectival_AS_phrase"]},
    {"name": "copula_tail_x$subexpression$1", "symbols": ["noun_phrase"]},
    {"name": "copula_tail_x$subexpression$1", "symbols": ["pronoun_xo"]},
    {"name": "copula_tail_x$subexpression$1", "symbols": ["demonstrative"]},
    {"name": "copula_tail_x$subexpression$1", "symbols": ["prepositional_phrase_N"]},
    {"name": "copula_tail_x", "symbols": ["_", "copula_tail_x$subexpression$1"]},
    {"name": "copula_tail_sA$subexpression$1", "symbols": ["adjective_phrase"]},
    {"name": "copula_tail_sA$subexpression$1", "symbols": ["adjectival_AS_phrase_sA"]},
    {"name": "copula_tail_sA$subexpression$1", "symbols": ["noun_phrase_sA"]},
    {"name": "copula_tail_sA$subexpression$1", "symbols": ["pronoun_soA"]},
    {"name": "copula_tail_sA$subexpression$1", "symbols": ["demonstrative_s"]},
    {"name": "copula_tail_sA$subexpression$1", "symbols": ["prepositional_phrase_N"]},
    {"name": "copula_tail_sA", "symbols": ["_", "copula_tail_sA$subexpression$1"]},
    {"name": "copula_tail_pA$subexpression$1", "symbols": ["adjective_phrase"]},
    {"name": "copula_tail_pA$subexpression$1", "symbols": ["adjectival_AS_phrase_pA"]},
    {"name": "copula_tail_pA$subexpression$1", "symbols": ["noun_phrase_pA"]},
    {"name": "copula_tail_pA$subexpression$1", "symbols": ["pronoun_poA"]},
    {"name": "copula_tail_pA$subexpression$1", "symbols": ["demonstrative_p"]},
    {"name": "copula_tail_pA$subexpression$1", "symbols": ["prepositional_phrase_N"]},
    {"name": "copula_tail_pA", "symbols": ["_", "copula_tail_pA$subexpression$1"]},
    {"name": "copula_tail_sI$subexpression$1", "symbols": ["adjective_phrase_I"]},
    {"name": "copula_tail_sI$subexpression$1", "symbols": ["adjectival_AS_phrase_sI"]},
    {"name": "copula_tail_sI$subexpression$1", "symbols": ["noun_phrase_sI"]},
    {"name": "copula_tail_sI$subexpression$1", "symbols": ["pronoun_soI"]},
    {"name": "copula_tail_sI$subexpression$1", "symbols": ["demonstrative_s"]},
    {"name": "copula_tail_sI$subexpression$1", "symbols": ["prepositional_phrase_N"]},
    {"name": "copula_tail_sI", "symbols": ["_", "copula_tail_sI$subexpression$1"]},
    {"name": "copula_tail_pI$subexpression$1", "symbols": ["adjective_phrase_I"]},
    {"name": "copula_tail_pI$subexpression$1", "symbols": ["adjectival_AS_phrase_pI"]},
    {"name": "copula_tail_pI$subexpression$1", "symbols": ["noun_phrase_pI"]},
    {"name": "copula_tail_pI$subexpression$1", "symbols": ["pronoun_poI"]},
    {"name": "copula_tail_pI$subexpression$1", "symbols": ["demonstrative_p"]},
    {"name": "copula_tail_pI$subexpression$1", "symbols": ["prepositional_phrase_N"]},
    {"name": "copula_tail_pI", "symbols": ["_", "copula_tail_pI$subexpression$1"]},
    {"name": "verb_2o_tail$subexpression$1", "symbols": ["noun_phrase"]},
    {"name": "verb_2o_tail$subexpression$1", "symbols": ["pronoun_xo"]},
    {"name": "verb_2o_tail", "symbols": ["_", "verb_2o_tail$subexpression$1"]},
    {"name": "possessive1", "symbols": ["1sp1"]},
    {"name": "possessive1", "symbols": ["1pp1"]},
    {"name": "possessive1", "symbols": ["2sp1"]},
    {"name": "possessive1", "symbols": ["2pp1"]},
    {"name": "possessive1", "symbols": ["3spM1"]},
    {"name": "possessive1", "symbols": ["3spF1"]},
    {"name": "possessive1", "symbols": ["3spN1"]},
    {"name": "possessive1", "symbols": ["3spI1"]},
    {"name": "possessive1", "symbols": ["3pp1"]},
    {"name": "possessive2", "symbols": ["1sp2"]},
    {"name": "possessive2", "symbols": ["1pp2"]},
    {"name": "possessive2", "symbols": ["2sp2"]},
    {"name": "possessive2", "symbols": ["2pp2"]},
    {"name": "possessive2", "symbols": ["3spM2"]},
    {"name": "possessive2", "symbols": ["3spF2"]},
    {"name": "possessive2", "symbols": ["3spN2"]},
    {"name": "possessive2", "symbols": ["3spI2"]},
    {"name": "possessive2", "symbols": ["3pp2"]},
    {"name": "pronoun_xo", "symbols": ["pronoun_soA"]},
    {"name": "pronoun_xo", "symbols": ["pronoun_soI"]},
    {"name": "pronoun_xo", "symbols": ["pronoun_poA"]},
    {"name": "pronoun_xo", "symbols": ["pronoun_poI"]},
    {"name": "pronoun_soA", "symbols": ["1so"]},
    {"name": "pronoun_soA", "symbols": ["2so"]},
    {"name": "pronoun_soA", "symbols": ["3soF"]},
    {"name": "pronoun_soA", "symbols": ["3soN"]},
    {"name": "pronoun_soA", "symbols": ["3soM"]},
    {"name": "pronoun_soA", "symbols": ["3soI"]},
    {"name": "pronoun_soI", "symbols": ["3soI"]},
    {"name": "pronoun_poA", "symbols": ["1po"]},
    {"name": "pronoun_poA", "symbols": ["2po"]},
    {"name": "pronoun_poA", "symbols": ["3po"]},
    {"name": "pronoun_poI", "symbols": ["3po"]},
    {"name": "noun_phrase", "symbols": ["noun_phrase_A"]},
    {"name": "noun_phrase", "symbols": ["noun_phrase_I"]},
    {"name": "noun_phrase_A", "symbols": ["noun_phrase_sA"]},
    {"name": "noun_phrase_A", "symbols": ["noun_phrase_pA"]},
    {"name": "noun_phrase_I", "symbols": ["noun_phrase_sI"]},
    {"name": "noun_phrase_I", "symbols": ["noun_phrase_pI"]},
    {"name": "noun_phrase_sA$subexpression$1", "symbols": ["possessive2"]},
    {"name": "noun_phrase_sA$subexpression$1$subexpression$1", "symbols": ["A_noun_sA"]},
    {"name": "noun_phrase_sA$subexpression$1$subexpression$1", "symbols": ["A_adjectives", "_", "noun_sA"]},
    {"name": "noun_phrase_sA$subexpression$1", "symbols": ["A", "_", "noun_phrase_sA$subexpression$1$subexpression$1"]},
    {"name": "noun_phrase_sA$subexpression$1$subexpression$2", "symbols": ["AN_noun_sA"]},
    {"name": "noun_phrase_sA$subexpression$1$subexpression$2", "symbols": ["AN_adjectives", "_", "noun_sA"]},
    {"name": "noun_phrase_sA$subexpression$1", "symbols": ["AN", "_", "noun_phrase_sA$subexpression$1$subexpression$2"]},
    {"name": "noun_phrase_sA$subexpression$1$subexpression$3", "symbols": ["THE"]},
    {"name": "noun_phrase_sA$subexpression$1$subexpression$3", "symbols": ["possessive1"]},
    {"name": "noun_phrase_sA$subexpression$1$subexpression$3", "symbols": ["demonstrative_s"]},
    {"name": "noun_phrase_sA$subexpression$1$ebnf$1$subexpression$1", "symbols": ["adjectives", "_"]},
    {"name": "noun_phrase_sA$subexpression$1$ebnf$1", "symbols": ["noun_phrase_sA$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "noun_phrase_sA$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noun_phrase_sA$subexpression$1", "symbols": ["noun_phrase_sA$subexpression$1$subexpression$3", "_", "noun_phrase_sA$subexpression$1$ebnf$1", "noun_sA"]},
    {"name": "noun_phrase_sA$ebnf$1$subexpression$1", "symbols": ["_", "OF_phrase"]},
    {"name": "noun_phrase_sA$ebnf$1", "symbols": ["noun_phrase_sA$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "noun_phrase_sA$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noun_phrase_sA$ebnf$2$subexpression$1", "symbols": ["_", "prepositional_phrase_N"]},
    {"name": "noun_phrase_sA$ebnf$2", "symbols": ["noun_phrase_sA$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "noun_phrase_sA$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noun_phrase_sA$ebnf$3$subexpression$1", "symbols": ["_", "property_subclause_sA"]},
    {"name": "noun_phrase_sA$ebnf$3", "symbols": ["noun_phrase_sA$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "noun_phrase_sA$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noun_phrase_sA", "symbols": ["noun_phrase_sA$subexpression$1", "noun_phrase_sA$ebnf$1", "noun_phrase_sA$ebnf$2", "noun_phrase_sA$ebnf$3"]},
    {"name": "noun_phrase_sI$subexpression$1", "symbols": ["possessive2"]},
    {"name": "noun_phrase_sI$subexpression$1$subexpression$1", "symbols": ["A_noun_sI"]},
    {"name": "noun_phrase_sI$subexpression$1$subexpression$1", "symbols": ["A_adjectives_I", "_", "noun_sI"]},
    {"name": "noun_phrase_sI$subexpression$1", "symbols": ["A", "_", "noun_phrase_sI$subexpression$1$subexpression$1"]},
    {"name": "noun_phrase_sI$subexpression$1$subexpression$2", "symbols": ["AN_noun_sI"]},
    {"name": "noun_phrase_sI$subexpression$1$subexpression$2", "symbols": ["AN_adjectives_I", "_", "noun_sI"]},
    {"name": "noun_phrase_sI$subexpression$1", "symbols": ["AN", "_", "noun_phrase_sI$subexpression$1$subexpression$2"]},
    {"name": "noun_phrase_sI$subexpression$1$subexpression$3", "symbols": ["THE"]},
    {"name": "noun_phrase_sI$subexpression$1$subexpression$3", "symbols": ["possessive1"]},
    {"name": "noun_phrase_sI$subexpression$1$subexpression$3", "symbols": ["demonstrative_s"]},
    {"name": "noun_phrase_sI$subexpression$1$ebnf$1$subexpression$1", "symbols": ["adjectives_I", "_"]},
    {"name": "noun_phrase_sI$subexpression$1$ebnf$1", "symbols": ["noun_phrase_sI$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "noun_phrase_sI$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noun_phrase_sI$subexpression$1", "symbols": ["noun_phrase_sI$subexpression$1$subexpression$3", "_", "noun_phrase_sI$subexpression$1$ebnf$1", "noun_sI"]},
    {"name": "noun_phrase_sI$ebnf$1$subexpression$1", "symbols": ["_", "OF_phrase"]},
    {"name": "noun_phrase_sI$ebnf$1", "symbols": ["noun_phrase_sI$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "noun_phrase_sI$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noun_phrase_sI$ebnf$2$subexpression$1", "symbols": ["_", "prepositional_phrase_N"]},
    {"name": "noun_phrase_sI$ebnf$2", "symbols": ["noun_phrase_sI$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "noun_phrase_sI$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noun_phrase_sI$ebnf$3$subexpression$1", "symbols": ["_", "property_subclause_sI"]},
    {"name": "noun_phrase_sI$ebnf$3", "symbols": ["noun_phrase_sI$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "noun_phrase_sI$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noun_phrase_sI", "symbols": ["noun_phrase_sI$subexpression$1", "noun_phrase_sI$ebnf$1", "noun_phrase_sI$ebnf$2", "noun_phrase_sI$ebnf$3"]},
    {"name": "noun_phrase_pI$subexpression$1", "symbols": ["possessive2"]},
    {"name": "noun_phrase_pI$subexpression$1$ebnf$1$subexpression$1$subexpression$1", "symbols": ["THE"]},
    {"name": "noun_phrase_pI$subexpression$1$ebnf$1$subexpression$1$subexpression$1", "symbols": ["possessive1"]},
    {"name": "noun_phrase_pI$subexpression$1$ebnf$1$subexpression$1$subexpression$1", "symbols": ["demonstrative_p"]},
    {"name": "noun_phrase_pI$subexpression$1$ebnf$1$subexpression$1", "symbols": ["noun_phrase_pI$subexpression$1$ebnf$1$subexpression$1$subexpression$1", "_"]},
    {"name": "noun_phrase_pI$subexpression$1$ebnf$1", "symbols": ["noun_phrase_pI$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "noun_phrase_pI$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noun_phrase_pI$subexpression$1$ebnf$2$subexpression$1", "symbols": ["adjectives_I", "_"]},
    {"name": "noun_phrase_pI$subexpression$1$ebnf$2", "symbols": ["noun_phrase_pI$subexpression$1$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "noun_phrase_pI$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noun_phrase_pI$subexpression$1", "symbols": ["noun_phrase_pI$subexpression$1$ebnf$1", "noun_phrase_pI$subexpression$1$ebnf$2", "noun_pI"]},
    {"name": "noun_phrase_pI$ebnf$1$subexpression$1", "symbols": ["_", "OF_phrase"]},
    {"name": "noun_phrase_pI$ebnf$1", "symbols": ["noun_phrase_pI$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "noun_phrase_pI$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noun_phrase_pI$ebnf$2$subexpression$1", "symbols": ["_", "prepositional_phrase_N"]},
    {"name": "noun_phrase_pI$ebnf$2", "symbols": ["noun_phrase_pI$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "noun_phrase_pI$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noun_phrase_pI$ebnf$3$subexpression$1", "symbols": ["_", "property_subclause_pI"]},
    {"name": "noun_phrase_pI$ebnf$3", "symbols": ["noun_phrase_pI$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "noun_phrase_pI$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noun_phrase_pI", "symbols": ["noun_phrase_pI$subexpression$1", "noun_phrase_pI$ebnf$1", "noun_phrase_pI$ebnf$2", "noun_phrase_pI$ebnf$3"]},
    {"name": "noun_phrase_pA$subexpression$1", "symbols": ["possessive2"]},
    {"name": "noun_phrase_pA$subexpression$1$ebnf$1$subexpression$1$subexpression$1", "symbols": ["THE"]},
    {"name": "noun_phrase_pA$subexpression$1$ebnf$1$subexpression$1$subexpression$1", "symbols": ["possessive1"]},
    {"name": "noun_phrase_pA$subexpression$1$ebnf$1$subexpression$1$subexpression$1", "symbols": ["demonstrative_p"]},
    {"name": "noun_phrase_pA$subexpression$1$ebnf$1$subexpression$1", "symbols": ["noun_phrase_pA$subexpression$1$ebnf$1$subexpression$1$subexpression$1", "_"]},
    {"name": "noun_phrase_pA$subexpression$1$ebnf$1", "symbols": ["noun_phrase_pA$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "noun_phrase_pA$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noun_phrase_pA$subexpression$1$ebnf$2$subexpression$1", "symbols": ["adjectives", "_"]},
    {"name": "noun_phrase_pA$subexpression$1$ebnf$2", "symbols": ["noun_phrase_pA$subexpression$1$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "noun_phrase_pA$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noun_phrase_pA$subexpression$1", "symbols": ["noun_phrase_pA$subexpression$1$ebnf$1", "noun_phrase_pA$subexpression$1$ebnf$2", "noun_pA"]},
    {"name": "noun_phrase_pA$ebnf$1$subexpression$1", "symbols": ["_", "OF_phrase"]},
    {"name": "noun_phrase_pA$ebnf$1", "symbols": ["noun_phrase_pA$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "noun_phrase_pA$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noun_phrase_pA$ebnf$2$subexpression$1", "symbols": ["_", "prepositional_phrase_N"]},
    {"name": "noun_phrase_pA$ebnf$2", "symbols": ["noun_phrase_pA$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "noun_phrase_pA$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noun_phrase_pA$ebnf$3$subexpression$1", "symbols": ["_", "property_subclause_pA"]},
    {"name": "noun_phrase_pA$ebnf$3", "symbols": ["noun_phrase_pA$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "noun_phrase_pA$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "noun_phrase_pA", "symbols": ["noun_phrase_pA$subexpression$1", "noun_phrase_pA$ebnf$1", "noun_phrase_pA$ebnf$2", "noun_phrase_pA$ebnf$3"]},
    {"name": "noun_sA", "symbols": ["A_noun_sA"]},
    {"name": "noun_sA", "symbols": ["AN_noun_sA"]},
    {"name": "noun_pA", "symbols": ["A_noun_pA"]},
    {"name": "noun_pA", "symbols": ["AN_noun_pA"]},
    {"name": "noun_sI", "symbols": ["A_noun_sI"]},
    {"name": "noun_sI", "symbols": ["AN_noun_sI"]},
    {"name": "noun_pI", "symbols": ["A_noun_pI"]},
    {"name": "noun_pI", "symbols": ["AN_noun_pI"]},
    {"name": "A_noun_sA$string$1", "symbols": [{"literal":"p"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "A_noun_sA", "symbols": ["A_noun_sA$string$1"]},
    {"name": "A_noun_sA$string$2", "symbols": [{"literal":"b"}, {"literal":"o"}, {"literal":"s"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "A_noun_sA", "symbols": ["A_noun_sA$string$2"]},
    {"name": "A_noun_sA$string$3", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"r"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "A_noun_sA", "symbols": ["A_noun_sA$string$3"]},
    {"name": "AN_noun_sA$string$1", "symbols": [{"literal":"u"}, {"literal":"n"}, {"literal":"c"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AN_noun_sA", "symbols": ["AN_noun_sA$string$1"]},
    {"name": "AN_noun_sA$string$2", "symbols": [{"literal":"a"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AN_noun_sA", "symbols": ["AN_noun_sA$string$2"]},
    {"name": "A_noun_pA$string$1", "symbols": [{"literal":"p"}, {"literal":"e"}, {"literal":"o"}, {"literal":"p"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "A_noun_pA", "symbols": ["A_noun_pA$string$1"]},
    {"name": "A_noun_pA$string$2", "symbols": [{"literal":"b"}, {"literal":"o"}, {"literal":"s"}, {"literal":"s"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "A_noun_pA", "symbols": ["A_noun_pA$string$2"]},
    {"name": "AN_noun_pA$string$1", "symbols": [{"literal":"u"}, {"literal":"n"}, {"literal":"c"}, {"literal":"l"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AN_noun_pA", "symbols": ["AN_noun_pA$string$1"]},
    {"name": "AN_noun_pA$string$2", "symbols": [{"literal":"a"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AN_noun_pA", "symbols": ["AN_noun_pA$string$2"]},
    {"name": "A_noun_sI$string$1", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"n"}, {"literal":"a"}, {"literal":"n"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "A_noun_sI", "symbols": ["A_noun_sI$string$1"]},
    {"name": "A_noun_sI$string$2", "symbols": [{"literal":"b"}, {"literal":"o"}, {"literal":"o"}, {"literal":"k"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "A_noun_sI", "symbols": ["A_noun_sI$string$2"]},
    {"name": "AN_noun_sI$string$1", "symbols": [{"literal":"a"}, {"literal":"p"}, {"literal":"p"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AN_noun_sI", "symbols": ["AN_noun_sI$string$1"]},
    {"name": "AN_noun_sI$string$2", "symbols": [{"literal":"e"}, {"literal":"y"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AN_noun_sI", "symbols": ["AN_noun_sI$string$2"]},
    {"name": "A_noun_pI$string$1", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"n"}, {"literal":"a"}, {"literal":"n"}, {"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "A_noun_pI", "symbols": ["A_noun_pI$string$1"]},
    {"name": "A_noun_pI$string$2", "symbols": [{"literal":"b"}, {"literal":"o"}, {"literal":"o"}, {"literal":"k"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "A_noun_pI", "symbols": ["A_noun_pI$string$2"]},
    {"name": "AN_noun_pI$string$1", "symbols": [{"literal":"a"}, {"literal":"p"}, {"literal":"p"}, {"literal":"l"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AN_noun_pI", "symbols": ["AN_noun_pI$string$1"]},
    {"name": "AN_noun_pI$string$2", "symbols": [{"literal":"e"}, {"literal":"y"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AN_noun_pI", "symbols": ["AN_noun_pI$string$2"]},
    {"name": "AN_noun_pI$string$3", "symbols": [{"literal":"o"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AN_noun_pI", "symbols": ["AN_noun_pI$string$3"]},
    {"name": "verb_2o_1s", "symbols": ["verb_2o_1s_pres"]},
    {"name": "verb_2o_1s", "symbols": ["verb_2o_1s_past"]},
    {"name": "verb_2o_1s", "symbols": ["WILL", "_", "verb_2o_infinitive"]},
    {"name": "verb_2o_1p", "symbols": ["verb_2o_1p_pres"]},
    {"name": "verb_2o_1p", "symbols": ["verb_2o_1p_past"]},
    {"name": "verb_2o_1p", "symbols": ["WILL", "_", "verb_2o_infinitive"]},
    {"name": "verb_2o_2s", "symbols": ["verb_2o_2s_pres"]},
    {"name": "verb_2o_2s", "symbols": ["verb_2o_2s_past"]},
    {"name": "verb_2o_2s", "symbols": ["WILL", "_", "verb_2o_infinitive"]},
    {"name": "verb_2o_2p", "symbols": ["verb_2o_2p_pres"]},
    {"name": "verb_2o_2p", "symbols": ["verb_2o_2p_past"]},
    {"name": "verb_2o_2p", "symbols": ["WILL", "_", "verb_2o_infinitive"]},
    {"name": "verb_2o_3sI", "symbols": ["verb_2o_3sI_pres"]},
    {"name": "verb_2o_3sI", "symbols": ["verb_2o_3sI_past"]},
    {"name": "verb_2o_3sI", "symbols": ["WILL", "_", "verb_2o_I_infinitive"]},
    {"name": "verb_2o_3pI", "symbols": ["verb_2o_3pI_pres"]},
    {"name": "verb_2o_3pI", "symbols": ["verb_2o_3pI_past"]},
    {"name": "verb_2o_3pI", "symbols": ["WILL", "_", "verb_2o_I_infinitive"]},
    {"name": "verb_2o_3s", "symbols": ["verb_2o_3sI_pres"]},
    {"name": "verb_2o_3s", "symbols": ["verb_2o_3sI_past"]},
    {"name": "verb_2o_3s", "symbols": ["WILL", "_", "verb_2o_infinitive"]},
    {"name": "verb_2o_3p", "symbols": ["verb_2o_3pI_pres"]},
    {"name": "verb_2o_3p", "symbols": ["verb_2o_3sI_past"]},
    {"name": "verb_2o_3p", "symbols": ["WILL", "_", "verb_2o_infinitive"]},
    {"name": "verb_2o_infinitive", "symbols": ["verb_2o_I_infinitive"]},
    {"name": "negative_verb_2o_1s", "symbols": ["DO_1s_pres", "_", "NOT", "_", "verb_2o_infinitive"]},
    {"name": "negative_verb_2o_1s", "symbols": ["DO_1s_past", "_", "NOT", "_", "verb_2o_infinitive"]},
    {"name": "negative_verb_2o_1s", "symbols": ["WILL", "_", "NOT", "_", "verb_2o_infinitive"]},
    {"name": "negative_verb_2o_1p", "symbols": ["DO_1p_pres", "_", "NOT", "_", "verb_2o_infinitive"]},
    {"name": "negative_verb_2o_1p", "symbols": ["DO_1p_past", "_", "NOT", "_", "verb_2o_infinitive"]},
    {"name": "negative_verb_2o_1p", "symbols": ["WILL", "_", "NOT", "_", "verb_2o_infinitive"]},
    {"name": "negative_verb_2o_2s", "symbols": ["DO_2s_pres", "_", "NOT", "_", "verb_2o_infinitive"]},
    {"name": "negative_verb_2o_2s", "symbols": ["DO_2s_past", "_", "NOT", "_", "verb_2o_infinitive"]},
    {"name": "negative_verb_2o_2s", "symbols": ["WILL", "_", "NOT", "_", "verb_2o_infinitive"]},
    {"name": "negative_verb_2o_2p", "symbols": ["DO_2p_pres", "_", "NOT", "_", "verb_2o_infinitive"]},
    {"name": "negative_verb_2o_2p", "symbols": ["DO_2p_past", "_", "NOT", "_", "verb_2o_infinitive"]},
    {"name": "negative_verb_2o_2p", "symbols": ["WILL", "_", "NOT", "_", "verb_2o_infinitive"]},
    {"name": "negative_verb_2o_3sI", "symbols": ["DO_3s_pres", "_", "NOT", "_", "verb_2o_I_infinitive"]},
    {"name": "negative_verb_2o_3sI", "symbols": ["DO_3s_past", "_", "NOT", "_", "verb_2o_infinitive"]},
    {"name": "negative_verb_2o_3sI", "symbols": ["WILL", "_", "NOT", "_", "verb_2o_infinitive"]},
    {"name": "negative_verb_2o_3pI", "symbols": ["DO_3p_pres", "_", "NOT", "_", "verb_2o_I_infinitive"]},
    {"name": "negative_verb_2o_3pI", "symbols": ["DO_3p_past", "_", "NOT", "_", "verb_2o_infinitive"]},
    {"name": "negative_verb_2o_3pI", "symbols": ["WILL", "_", "NOT", "_", "verb_2o_infinitive"]},
    {"name": "negative_verb_2o_3s", "symbols": ["DO_3s_pres", "_", "NOT", "_", "verb_2o_infinitive"]},
    {"name": "negative_verb_2o_3s", "symbols": ["DO_3s_past", "_", "NOT", "_", "verb_2o_infinitive"]},
    {"name": "negative_verb_2o_3s", "symbols": ["WILL", "_", "NOT", "_", "verb_2o_infinitive"]},
    {"name": "negative_verb_2o_3p", "symbols": ["DO_3p_pres", "_", "NOT", "_", "verb_2o_infinitive"]},
    {"name": "negative_verb_2o_3p", "symbols": ["DO_3p_past", "_", "NOT", "_", "verb_2o_infinitive"]},
    {"name": "negative_verb_2o_3p", "symbols": ["WILL", "_", "NOT", "_", "verb_2o_infinitive"]},
    {"name": "1s_copula$subexpression$1", "symbols": ["BE_1s_past"]},
    {"name": "1s_copula$subexpression$1", "symbols": ["BE_1s_pres"]},
    {"name": "1s_copula$subexpression$1", "symbols": ["WILL", "_", "BE"]},
    {"name": "1s_copula$subexpression$1", "symbols": ["HAVE_1s_pres", "_", "BE_perf"]},
    {"name": "1s_copula$subexpression$1", "symbols": ["HAVE_1s_past", "_", "BE_perf"]},
    {"name": "1s_copula", "symbols": ["1s_copula$subexpression$1"]},
    {"name": "1p_copula$subexpression$1", "symbols": ["BE_1p_past"]},
    {"name": "1p_copula$subexpression$1", "symbols": ["BE_1p_pres"]},
    {"name": "1p_copula$subexpression$1", "symbols": ["WILL", "_", "BE"]},
    {"name": "1p_copula$subexpression$1", "symbols": ["HAVE_1p_pres", "_", "BE_perf"]},
    {"name": "1p_copula$subexpression$1", "symbols": ["HAVE_1p_past", "_", "BE_perf"]},
    {"name": "1p_copula", "symbols": ["1p_copula$subexpression$1"]},
    {"name": "2s_copula$subexpression$1", "symbols": ["BE_2s_past"]},
    {"name": "2s_copula$subexpression$1", "symbols": ["BE_2s_pres"]},
    {"name": "2s_copula$subexpression$1", "symbols": ["WILL", "_", "BE"]},
    {"name": "2s_copula$subexpression$1", "symbols": ["HAVE_2s_pres", "_", "BE_perf"]},
    {"name": "2s_copula$subexpression$1", "symbols": ["HAVE_2s_past", "_", "BE_perf"]},
    {"name": "2s_copula", "symbols": ["2s_copula$subexpression$1"]},
    {"name": "2p_copula$subexpression$1", "symbols": ["BE_2p_past"]},
    {"name": "2p_copula$subexpression$1", "symbols": ["BE_2p_pres"]},
    {"name": "2p_copula$subexpression$1", "symbols": ["WILL", "_", "BE"]},
    {"name": "2p_copula$subexpression$1", "symbols": ["HAVE_2p_pres", "_", "BE_perf"]},
    {"name": "2p_copula$subexpression$1", "symbols": ["HAVE_2p_past", "_", "BE_perf"]},
    {"name": "2p_copula", "symbols": ["2p_copula$subexpression$1"]},
    {"name": "3s_copula$subexpression$1", "symbols": ["BE_3s_past"]},
    {"name": "3s_copula$subexpression$1", "symbols": ["BE_3s_pres"]},
    {"name": "3s_copula$subexpression$1", "symbols": ["WILL", "_", "BE"]},
    {"name": "3s_copula$subexpression$1", "symbols": ["HAVE_3s_pres", "_", "BE_perf"]},
    {"name": "3s_copula$subexpression$1", "symbols": ["HAVE_3s_past", "_", "BE_perf"]},
    {"name": "3s_copula", "symbols": ["3s_copula$subexpression$1"]},
    {"name": "3p_copula$subexpression$1", "symbols": ["BE_3p_past"]},
    {"name": "3p_copula$subexpression$1", "symbols": ["BE_3p_pres"]},
    {"name": "3p_copula$subexpression$1", "symbols": ["WILL", "_", "BE"]},
    {"name": "3p_copula$subexpression$1", "symbols": ["HAVE_3p_pres", "_", "BE_perf"]},
    {"name": "3p_copula$subexpression$1", "symbols": ["HAVE_3p_past", "_", "BE_perf"]},
    {"name": "3p_copula", "symbols": ["3p_copula$subexpression$1"]},
    {"name": "1s_negative_copula$subexpression$1", "symbols": ["BE_1s_past", "_", "NOT"]},
    {"name": "1s_negative_copula$subexpression$1", "symbols": ["BE_1s_pres", "_", "NOT"]},
    {"name": "1s_negative_copula$subexpression$1", "symbols": ["WILL", "_", "NOT", "_", "BE"]},
    {"name": "1s_negative_copula$subexpression$1", "symbols": ["HAVE_1s_pres", "_", "NOT", "_", "BE_perf"]},
    {"name": "1s_negative_copula$subexpression$1", "symbols": ["HAVE_1s_past", "_", "NOT", "_", "BE_perf"]},
    {"name": "1s_negative_copula", "symbols": ["1s_negative_copula$subexpression$1"]},
    {"name": "1p_negative_copula$subexpression$1", "symbols": ["BE_1p_past", "_", "NOT"]},
    {"name": "1p_negative_copula$subexpression$1", "symbols": ["BE_1p_pres", "_", "NOT"]},
    {"name": "1p_negative_copula$subexpression$1", "symbols": ["WILL", "_", "NOT", "_", "BE"]},
    {"name": "1p_negative_copula$subexpression$1", "symbols": ["HAVE_1p_pres", "_", "NOT", "_", "BE_perf"]},
    {"name": "1p_negative_copula$subexpression$1", "symbols": ["HAVE_1p_past", "_", "NOT", "_", "BE_perf"]},
    {"name": "1p_negative_copula", "symbols": ["1p_negative_copula$subexpression$1"]},
    {"name": "2s_negative_copula$subexpression$1", "symbols": ["BE_2s_past", "_", "NOT"]},
    {"name": "2s_negative_copula$subexpression$1", "symbols": ["BE_2s_pres", "_", "NOT"]},
    {"name": "2s_negative_copula$subexpression$1", "symbols": ["WILL", "_", "NOT", "_", "BE"]},
    {"name": "2s_negative_copula$subexpression$1", "symbols": ["HAVE_2s_pres", "_", "NOT", "_", "BE_perf"]},
    {"name": "2s_negative_copula$subexpression$1", "symbols": ["HAVE_2s_past", "_", "NOT", "_", "BE_perf"]},
    {"name": "2s_negative_copula", "symbols": ["2s_negative_copula$subexpression$1"]},
    {"name": "2p_negative_copula$subexpression$1", "symbols": ["BE_2p_past", "_", "NOT"]},
    {"name": "2p_negative_copula$subexpression$1", "symbols": ["BE_2p_pres", "_", "NOT"]},
    {"name": "2p_negative_copula$subexpression$1", "symbols": ["WILL", "_", "NOT", "_", "BE"]},
    {"name": "2p_negative_copula$subexpression$1", "symbols": ["HAVE_2p_pres", "_", "NOT", "_", "BE_perf"]},
    {"name": "2p_negative_copula$subexpression$1", "symbols": ["HAVE_2p_past", "_", "NOT", "_", "BE_perf"]},
    {"name": "2p_negative_copula", "symbols": ["2p_negative_copula$subexpression$1"]},
    {"name": "3s_negative_copula$subexpression$1", "symbols": ["BE_3s_past", "_", "NOT"]},
    {"name": "3s_negative_copula$subexpression$1", "symbols": ["BE_3s_pres", "_", "NOT"]},
    {"name": "3s_negative_copula$subexpression$1", "symbols": ["WILL", "_", "NOT", "_", "BE"]},
    {"name": "3s_negative_copula$subexpression$1", "symbols": ["HAVE_3s_pres", "_", "NOT", "_", "BE_perf"]},
    {"name": "3s_negative_copula$subexpression$1", "symbols": ["HAVE_3s_past", "_", "NOT", "_", "BE_perf"]},
    {"name": "3s_negative_copula", "symbols": ["3s_negative_copula$subexpression$1"]},
    {"name": "3p_negative_copula$subexpression$1", "symbols": ["BE_3p_past", "_", "NOT"]},
    {"name": "3p_negative_copula$subexpression$1", "symbols": ["BE_3p_pres", "_", "NOT"]},
    {"name": "3p_negative_copula$subexpression$1", "symbols": ["WILL", "_", "NOT", "_", "BE"]},
    {"name": "3p_negative_copula$subexpression$1", "symbols": ["HAVE_3p_pres", "_", "NOT", "_", "BE_perf"]},
    {"name": "3p_negative_copula$subexpression$1", "symbols": ["HAVE_3p_past", "_", "NOT", "_", "BE_perf"]},
    {"name": "3p_negative_copula", "symbols": ["3p_negative_copula$subexpression$1"]},
    {"name": "adjectives", "symbols": ["A_adjectives"]},
    {"name": "adjectives", "symbols": ["AN_adjectives"]},
    {"name": "adjectives_I", "symbols": ["A_adjectives_I"]},
    {"name": "adjectives_I", "symbols": ["AN_adjectives_I"]},
    {"name": "A_adjectives$ebnf$1", "symbols": []},
    {"name": "A_adjectives$ebnf$1$subexpression$1", "symbols": ["_", "adjective"]},
    {"name": "A_adjectives$ebnf$1", "symbols": ["A_adjectives$ebnf$1", "A_adjectives$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "A_adjectives", "symbols": ["A_adjective_phrase", "A_adjectives$ebnf$1"]},
    {"name": "AN_adjectives$ebnf$1", "symbols": []},
    {"name": "AN_adjectives$ebnf$1$subexpression$1", "symbols": ["_", "adjective"]},
    {"name": "AN_adjectives$ebnf$1", "symbols": ["AN_adjectives$ebnf$1", "AN_adjectives$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "AN_adjectives", "symbols": ["AN_adjective_phrase", "AN_adjectives$ebnf$1"]},
    {"name": "A_adjectives_I$ebnf$1", "symbols": []},
    {"name": "A_adjectives_I$ebnf$1$subexpression$1", "symbols": ["_", "adjective_I"]},
    {"name": "A_adjectives_I$ebnf$1", "symbols": ["A_adjectives_I$ebnf$1", "A_adjectives_I$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "A_adjectives_I", "symbols": ["A_adjective_I", "A_adjectives_I$ebnf$1"]},
    {"name": "AN_adjectives_I$ebnf$1", "symbols": []},
    {"name": "AN_adjectives_I$ebnf$1$subexpression$1", "symbols": ["_", "adjective_I"]},
    {"name": "AN_adjectives_I$ebnf$1", "symbols": ["AN_adjectives_I$ebnf$1", "AN_adjectives_I$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "AN_adjectives_I", "symbols": ["AN_adjective_I", "AN_adjectives_I$ebnf$1"]},
    {"name": "adjective_phrase", "symbols": ["adjective_phrase_A"]},
    {"name": "adjective_phrase", "symbols": ["adjective_phrase_I"]},
    {"name": "adjective_phrase_A", "symbols": ["A_adjective_phrase_A"]},
    {"name": "adjective_phrase_A", "symbols": ["AN_adjective_phrase_A"]},
    {"name": "adjective_phrase_I", "symbols": ["A_adjective_phrase_I"]},
    {"name": "adjective_phrase_I", "symbols": ["AN_adjective_phrase_I"]},
    {"name": "A_adjective_phrase", "symbols": ["A_adjective_phrase_A"]},
    {"name": "A_adjective_phrase", "symbols": ["A_adjective_phrase_I"]},
    {"name": "AN_adjective_phrase", "symbols": ["AN_adjective_phrase_A"]},
    {"name": "AN_adjective_phrase", "symbols": ["AN_adjective_phrase_I"]},
    {"name": "A_adjective_phrase_A", "symbols": ["A_adjective_A"]},
    {"name": "A_adjective_phrase_A", "symbols": ["A_adverb", "_", "adjective_A"]},
    {"name": "A_adjective_phrase_I", "symbols": ["A_adjective_I"]},
    {"name": "A_adjective_phrase_I", "symbols": ["A_adverb", "_", "adjective_I"]},
    {"name": "AN_adjective_phrase_A", "symbols": ["AN_adjective_A"]},
    {"name": "AN_adjective_phrase_A", "symbols": ["AN_adverb", "_", "adjective_A"]},
    {"name": "AN_adjective_phrase_I", "symbols": ["AN_adjective_I"]},
    {"name": "AN_adjective_phrase_I", "symbols": ["AN_adverb", "_", "adjective_I"]},
    {"name": "adjective", "symbols": ["adjective_A"]},
    {"name": "adjective", "symbols": ["adjective_I"]},
    {"name": "adjective_A", "symbols": ["A_adjective_A"]},
    {"name": "adjective_A", "symbols": ["AN_adjective_A"]},
    {"name": "adjective_I", "symbols": ["A_adjective_I"]},
    {"name": "adjective_I", "symbols": ["AN_adjective_I"]},
    {"name": "A_adjective", "symbols": ["A_adjective_A"]},
    {"name": "A_adjective", "symbols": ["A_adjective_I"]},
    {"name": "AN_adjective", "symbols": ["AN_adjective_A"]},
    {"name": "AN_adjective", "symbols": ["AN_adjective_I"]},
    {"name": "A_adjective_A$string$1", "symbols": [{"literal":"s"}, {"literal":"m"}, {"literal":"a"}, {"literal":"r"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "A_adjective_A", "symbols": ["A_adjective_A$string$1"]},
    {"name": "A_adjective_A$string$2", "symbols": [{"literal":"f"}, {"literal":"r"}, {"literal":"i"}, {"literal":"e"}, {"literal":"n"}, {"literal":"d"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "A_adjective_A", "symbols": ["A_adjective_A$string$2"]},
    {"name": "A_adjective_A$string$3", "symbols": [{"literal":"p"}, {"literal":"r"}, {"literal":"e"}, {"literal":"t"}, {"literal":"t"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "A_adjective_A", "symbols": ["A_adjective_A$string$3"]},
    {"name": "A_adjective_I$string$1", "symbols": [{"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "A_adjective_I", "symbols": ["A_adjective_I$string$1"]},
    {"name": "A_adjective_I$string$2", "symbols": [{"literal":"t"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "A_adjective_I", "symbols": ["A_adjective_I$string$2"]},
    {"name": "AN_adjective_A$string$1", "symbols": [{"literal":"e"}, {"literal":"n"}, {"literal":"e"}, {"literal":"r"}, {"literal":"g"}, {"literal":"e"}, {"literal":"t"}, {"literal":"i"}, {"literal":"c"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AN_adjective_A", "symbols": ["AN_adjective_A$string$1"]},
    {"name": "AN_adjective_A$string$2", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AN_adjective_A", "symbols": ["AN_adjective_A$string$2"]},
    {"name": "AN_adjective_I$string$1", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":"a"}, {"literal":"z"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AN_adjective_I", "symbols": ["AN_adjective_I$string$1"]},
    {"name": "AN_adjective_I$string$2", "symbols": [{"literal":"o"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AN_adjective_I", "symbols": ["AN_adjective_I$string$2"]},
    {"name": "adverb", "symbols": ["A_adverb"]},
    {"name": "adverb", "symbols": ["AN_adverb"]},
    {"name": "A_adverb$string$1", "symbols": [{"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "A_adverb", "symbols": ["A_adverb$string$1"]},
    {"name": "A_adverb$string$2", "symbols": [{"literal":"m"}, {"literal":"i"}, {"literal":"l"}, {"literal":"d"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "A_adverb", "symbols": ["A_adverb$string$2"]},
    {"name": "AN_adverb$string$1", "symbols": [{"literal":"u"}, {"literal":"n"}, {"literal":"u"}, {"literal":"s"}, {"literal":"u"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AN_adverb", "symbols": ["AN_adverb$string$1"]},
    {"name": "AN_adverb$string$2", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"u"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AN_adverb", "symbols": ["AN_adverb$string$2"]},
    {"name": "OF_phrase$subexpression$1", "symbols": ["noun_phrase"]},
    {"name": "OF_phrase$subexpression$1", "symbols": ["pronoun_xo"]},
    {"name": "OF_phrase", "symbols": ["OF", "_", "OF_phrase$subexpression$1"]},
    {"name": "prepositional_phrase", "symbols": ["prepositional_phrase_N"]},
    {"name": "prepositional_phrase_N$subexpression$1", "symbols": ["noun_phrase"]},
    {"name": "prepositional_phrase_N$subexpression$1", "symbols": ["pronoun_xo"]},
    {"name": "prepositional_phrase_N", "symbols": ["preposition_N", "_", "prepositional_phrase_N$subexpression$1"]},
    {"name": "preposition_N", "symbols": ["preposition_ND"]},
    {"name": "preposition_N", "symbols": ["preposition_NI"]},
    {"name": "property_subclause_sA$ebnf$1$subexpression$1", "symbols": ["subclause_conjunction_P", "_"]},
    {"name": "property_subclause_sA$ebnf$1", "symbols": ["property_subclause_sA$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "property_subclause_sA$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "property_subclause_sA$subexpression$1", "symbols": ["copula_base_sA"]},
    {"name": "property_subclause_sA$subexpression$1", "symbols": ["verb_2o_base"]},
    {"name": "property_subclause_sA", "symbols": ["property_subclause_sA$ebnf$1", "property_subclause_sA$subexpression$1"]},
    {"name": "property_subclause_sA$subexpression$2$subexpression$1", "symbols": ["3s_copula"]},
    {"name": "property_subclause_sA$subexpression$2$subexpression$1", "symbols": ["3s_negative_copula"]},
    {"name": "property_subclause_sA$subexpression$2", "symbols": ["property_subclause_sA$subexpression$2$subexpression$1", "copula_tail_sA"]},
    {"name": "property_subclause_sA$subexpression$2$subexpression$2", "symbols": ["verb_2o_3s"]},
    {"name": "property_subclause_sA$subexpression$2$subexpression$2", "symbols": ["negative_verb_2o_3s"]},
    {"name": "property_subclause_sA$subexpression$2", "symbols": ["property_subclause_sA$subexpression$2$subexpression$2", "verb_2o_tail"]},
    {"name": "property_subclause_sA", "symbols": ["subclause_conjunction_P", "_", "property_subclause_sA$subexpression$2"]},
    {"name": "property_subclause_sI$ebnf$1$subexpression$1", "symbols": ["subclause_conjunction_P", "_"]},
    {"name": "property_subclause_sI$ebnf$1", "symbols": ["property_subclause_sI$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "property_subclause_sI$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "property_subclause_sI$subexpression$1", "symbols": ["copula_base_sI"]},
    {"name": "property_subclause_sI$subexpression$1", "symbols": ["verb_2o_base"]},
    {"name": "property_subclause_sI", "symbols": ["property_subclause_sI$ebnf$1", "property_subclause_sI$subexpression$1"]},
    {"name": "property_subclause_sI$subexpression$2$subexpression$1", "symbols": ["3s_copula"]},
    {"name": "property_subclause_sI$subexpression$2$subexpression$1", "symbols": ["3s_negative_copula"]},
    {"name": "property_subclause_sI$subexpression$2", "symbols": ["property_subclause_sI$subexpression$2$subexpression$1", "copula_tail_sI"]},
    {"name": "property_subclause_sI$subexpression$2$subexpression$2", "symbols": ["verb_2o_3s"]},
    {"name": "property_subclause_sI$subexpression$2$subexpression$2", "symbols": ["negative_verb_2o_3s"]},
    {"name": "property_subclause_sI$subexpression$2", "symbols": ["property_subclause_sI$subexpression$2$subexpression$2", "verb_2o_tail"]},
    {"name": "property_subclause_sI", "symbols": ["subclause_conjunction_P", "_", "property_subclause_sI$subexpression$2"]},
    {"name": "property_subclause_pA$ebnf$1$subexpression$1", "symbols": ["subclause_conjunction_P", "_"]},
    {"name": "property_subclause_pA$ebnf$1", "symbols": ["property_subclause_pA$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "property_subclause_pA$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "property_subclause_pA$subexpression$1", "symbols": ["copula_base_pA"]},
    {"name": "property_subclause_pA$subexpression$1", "symbols": ["verb_2o_base"]},
    {"name": "property_subclause_pA", "symbols": ["property_subclause_pA$ebnf$1", "property_subclause_pA$subexpression$1"]},
    {"name": "property_subclause_pA$subexpression$2$subexpression$1", "symbols": ["3p_copula"]},
    {"name": "property_subclause_pA$subexpression$2$subexpression$1", "symbols": ["3p_negative_copula"]},
    {"name": "property_subclause_pA$subexpression$2", "symbols": ["property_subclause_pA$subexpression$2$subexpression$1", "copula_tail_pA"]},
    {"name": "property_subclause_pA$subexpression$2$subexpression$2", "symbols": ["verb_2o_3p"]},
    {"name": "property_subclause_pA$subexpression$2$subexpression$2", "symbols": ["negative_verb_2o_3p"]},
    {"name": "property_subclause_pA$subexpression$2", "symbols": ["property_subclause_pA$subexpression$2$subexpression$2", "verb_2o_tail"]},
    {"name": "property_subclause_pA", "symbols": ["subclause_conjunction_P", "_", "property_subclause_pA$subexpression$2"]},
    {"name": "property_subclause_pI$ebnf$1$subexpression$1", "symbols": ["subclause_conjunction_P", "_"]},
    {"name": "property_subclause_pI$ebnf$1", "symbols": ["property_subclause_pI$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "property_subclause_pI$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "property_subclause_pI$subexpression$1", "symbols": ["copula_base_pI"]},
    {"name": "property_subclause_pI$subexpression$1", "symbols": ["verb_2o_base"]},
    {"name": "property_subclause_pI", "symbols": ["property_subclause_pI$ebnf$1", "property_subclause_pI$subexpression$1"]},
    {"name": "property_subclause_pI$subexpression$2$subexpression$1", "symbols": ["3p_copula"]},
    {"name": "property_subclause_pI$subexpression$2$subexpression$1", "symbols": ["3p_negative_copula"]},
    {"name": "property_subclause_pI$subexpression$2", "symbols": ["property_subclause_pI$subexpression$2$subexpression$1", "copula_tail_pI"]},
    {"name": "property_subclause_pI$subexpression$2$subexpression$2", "symbols": ["verb_2o_3p"]},
    {"name": "property_subclause_pI$subexpression$2$subexpression$2", "symbols": ["negative_verb_2o_3p"]},
    {"name": "property_subclause_pI$subexpression$2", "symbols": ["property_subclause_pI$subexpression$2$subexpression$2", "verb_2o_tail"]},
    {"name": "property_subclause_pI", "symbols": ["subclause_conjunction_P", "_", "property_subclause_pI$subexpression$2"]},
    {"name": "adjectival_AS_phrase", "symbols": ["adjectival_AS_phrase_sA"]},
    {"name": "adjectival_AS_phrase", "symbols": ["adjectival_AS_phrase_sI"]},
    {"name": "adjectival_AS_phrase", "symbols": ["adjectival_AS_phrase_pA"]},
    {"name": "adjectival_AS_phrase", "symbols": ["adjectival_AS_phrase_pI"]},
    {"name": "adjectival_AS_phrase_sA", "symbols": ["AS_comparative", "_", "adjective_I", "_", "AS_comparative", "_", "noun_phrase"]},
    {"name": "adjectival_AS_phrase_sA", "symbols": ["AS_comparative", "_", "adjective_A", "_", "AS_comparative", "_", "noun_phrase_A"]},
    {"name": "adjectival_AS_phrase_pA", "symbols": ["AS_comparative", "_", "adjective_I", "_", "AS_comparative", "_", "noun_phrase"]},
    {"name": "adjectival_AS_phrase_pA", "symbols": ["AS_comparative", "_", "adjective_A", "_", "AS_comparative", "_", "noun_phrase_A"]},
    {"name": "adjectival_AS_phrase_sI", "symbols": ["AS_comparative", "_", "adjective_I", "_", "AS_comparative", "_", "noun_phrase"]},
    {"name": "adjectival_AS_phrase_pI", "symbols": ["AS_comparative", "_", "adjective_I", "_", "AS_comparative", "_", "noun_phrase"]},
    {"name": "demonstrative", "symbols": ["demonstrative_p"]},
    {"name": "demonstrative", "symbols": ["demonstrative_s"]},
    {"name": "_", "symbols": [{"literal":" "}]},
    {"name": "A", "symbols": [{"literal":"a"}]},
    {"name": "BE_1s_pres$string$1", "symbols": [{"literal":"a"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BE_1s_pres", "symbols": ["BE_1s_pres$string$1"]},
    {"name": "AN$string$1", "symbols": [{"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AN", "symbols": ["AN$string$1"]},
    {"name": "symmetrical_conjuntion$string$1", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "symmetrical_conjuntion", "symbols": ["symmetrical_conjuntion$string$1"]},
    {"name": "AS_comparative$string$1", "symbols": [{"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AS_comparative", "symbols": ["AS_comparative$string$1"]},
    {"name": "preposition_ND$string$1", "symbols": [{"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition_ND", "symbols": ["preposition_ND$string$1"]},
    {"name": "preposition_VD$string$1", "symbols": [{"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition_VD", "symbols": ["preposition_VD$string$1"]},
    {"name": "BE_1p_pres$string$1", "symbols": [{"literal":"a"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BE_1p_pres", "symbols": ["BE_1p_pres$string$1"]},
    {"name": "BE_2s_pres$string$1", "symbols": [{"literal":"a"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BE_2s_pres", "symbols": ["BE_2s_pres$string$1"]},
    {"name": "BE_2p_pres$string$1", "symbols": [{"literal":"a"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BE_2p_pres", "symbols": ["BE_2p_pres$string$1"]},
    {"name": "BE_3p_pres$string$1", "symbols": [{"literal":"a"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BE_3p_pres", "symbols": ["BE_3p_pres$string$1"]},
    {"name": "preposition_ND$string$2", "symbols": [{"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition_ND", "symbols": ["preposition_ND$string$2"]},
    {"name": "A_purpose_adjective$string$1", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"k"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "A_purpose_adjective", "symbols": ["A_purpose_adjective$string$1"]},
    {"name": "BE$string$1", "symbols": [{"literal":"b"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BE", "symbols": ["BE$string$1"]},
    {"name": "BE_perf$string$1", "symbols": [{"literal":"b"}, {"literal":"e"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BE_perf", "symbols": ["BE_perf$string$1"]},
    {"name": "BE_ING$string$1", "symbols": [{"literal":"b"}, {"literal":"e"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BE_ING", "symbols": ["BE_ING$string$1"]},
    {"name": "A_size_adjective$string$1", "symbols": [{"literal":"b"}, {"literal":"i"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "A_size_adjective", "symbols": ["A_size_adjective$string$1"]},
    {"name": "preposition_NI$string$1", "symbols": [{"literal":"b"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition_NI", "symbols": ["preposition_NI$string$1"]},
    {"name": "DO_1s_past$string$1", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO_1s_past", "symbols": ["DO_1s_past$string$1"]},
    {"name": "DO_1p_past$string$1", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO_1p_past", "symbols": ["DO_1p_past$string$1"]},
    {"name": "DO_2s_past$string$1", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO_2s_past", "symbols": ["DO_2s_past$string$1"]},
    {"name": "DO_2p_past$string$1", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO_2p_past", "symbols": ["DO_2p_past$string$1"]},
    {"name": "DO_3s_past$string$1", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO_3s_past", "symbols": ["DO_3s_past$string$1"]},
    {"name": "DO_3p_past$string$1", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO_3p_past", "symbols": ["DO_3p_past$string$1"]},
    {"name": "DO$string$1", "symbols": [{"literal":"d"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO", "symbols": ["DO$string$1"]},
    {"name": "DO_1s_pres$string$1", "symbols": [{"literal":"d"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO_1s_pres", "symbols": ["DO_1s_pres$string$1"]},
    {"name": "DO_1p_pres$string$1", "symbols": [{"literal":"d"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO_1p_pres", "symbols": ["DO_1p_pres$string$1"]},
    {"name": "DO_2s_pres$string$1", "symbols": [{"literal":"d"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO_2s_pres", "symbols": ["DO_2s_pres$string$1"]},
    {"name": "DO_2p_pres$string$1", "symbols": [{"literal":"d"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO_2p_pres", "symbols": ["DO_2p_pres$string$1"]},
    {"name": "DO_3p_pres$string$1", "symbols": [{"literal":"d"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO_3p_pres", "symbols": ["DO_3p_pres$string$1"]},
    {"name": "DO_3s_pres$string$1", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO_3s_pres", "symbols": ["DO_3s_pres$string$1"]},
    {"name": "A_opinion_adjective$string$1", "symbols": [{"literal":"g"}, {"literal":"o"}, {"literal":"o"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "A_opinion_adjective", "symbols": ["A_opinion_adjective$string$1"]},
    {"name": "preposition_ND$string$3", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition_ND", "symbols": ["preposition_ND$string$3"]},
    {"name": "HAVE_1s_past$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HAVE_1s_past", "symbols": ["HAVE_1s_past$string$1"]},
    {"name": "HAVE_1p_past$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HAVE_1p_past", "symbols": ["HAVE_1p_past$string$1"]},
    {"name": "HAVE_2s_past$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HAVE_2s_past", "symbols": ["HAVE_2s_past$string$1"]},
    {"name": "HAVE_2p_past$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HAVE_2p_past", "symbols": ["HAVE_2p_past$string$1"]},
    {"name": "HAVE_3s_past$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HAVE_3s_past", "symbols": ["HAVE_3s_past$string$1"]},
    {"name": "HAVE_3p_past$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HAVE_3p_past", "symbols": ["HAVE_3p_past$string$1"]},
    {"name": "verb_2o_1s_past$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb_2o_1s_past", "symbols": ["verb_2o_1s_past$string$1"]},
    {"name": "verb_2o_1p_past$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb_2o_1p_past", "symbols": ["verb_2o_1p_past$string$1"]},
    {"name": "verb_2o_2s_past$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb_2o_2s_past", "symbols": ["verb_2o_2s_past$string$1"]},
    {"name": "verb_2o_2p_past$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb_2o_2p_past", "symbols": ["verb_2o_2p_past$string$1"]},
    {"name": "verb_2o_3sI_past$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb_2o_3sI_past", "symbols": ["verb_2o_3sI_past$string$1"]},
    {"name": "verb_2o_3pI_past$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb_2o_3pI_past", "symbols": ["verb_2o_3pI_past$string$1"]},
    {"name": "HAVE_3s_pres$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HAVE_3s_pres", "symbols": ["HAVE_3s_pres$string$1"]},
    {"name": "verb_2o_3sI_pres$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb_2o_3sI_pres", "symbols": ["verb_2o_3sI_pres$string$1"]},
    {"name": "HAVE$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HAVE", "symbols": ["HAVE$string$1"]},
    {"name": "HAVE_1s_pres$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HAVE_1s_pres", "symbols": ["HAVE_1s_pres$string$1"]},
    {"name": "HAVE_1p_pres$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HAVE_1p_pres", "symbols": ["HAVE_1p_pres$string$1"]},
    {"name": "HAVE_2s_pres$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HAVE_2s_pres", "symbols": ["HAVE_2s_pres$string$1"]},
    {"name": "HAVE_2p_pres$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HAVE_2p_pres", "symbols": ["HAVE_2p_pres$string$1"]},
    {"name": "HAVE_3p_pres$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "HAVE_3p_pres", "symbols": ["HAVE_3p_pres$string$1"]},
    {"name": "verb_2o_I_infinitive$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb_2o_I_infinitive", "symbols": ["verb_2o_I_infinitive$string$1"]},
    {"name": "verb_2o_1s_pres$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb_2o_1s_pres", "symbols": ["verb_2o_1s_pres$string$1"]},
    {"name": "verb_2o_1p_pres$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb_2o_1p_pres", "symbols": ["verb_2o_1p_pres$string$1"]},
    {"name": "verb_2o_2s_pres$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb_2o_2s_pres", "symbols": ["verb_2o_2s_pres$string$1"]},
    {"name": "verb_2o_2p_pres$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb_2o_2p_pres", "symbols": ["verb_2o_2p_pres$string$1"]},
    {"name": "verb_2o_3pI_pres$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb_2o_3pI_pres", "symbols": ["verb_2o_3pI_pres$string$1"]},
    {"name": "3ssM$string$1", "symbols": [{"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3ssM", "symbols": ["3ssM$string$1"]},
    {"name": "3soF$string$1", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3soF", "symbols": ["3soF$string$1"]},
    {"name": "3spF1$string$1", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3spF1", "symbols": ["3spF1$string$1"]},
    {"name": "3spF2$string$1", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3spF2", "symbols": ["3spF2$string$1"]},
    {"name": "3srF$string$1", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3srF", "symbols": ["3srF$string$1"]},
    {"name": "3soM$string$1", "symbols": [{"literal":"h"}, {"literal":"i"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3soM", "symbols": ["3soM$string$1"]},
    {"name": "3srM$string$1", "symbols": [{"literal":"h"}, {"literal":"i"}, {"literal":"m"}, {"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3srM", "symbols": ["3srM$string$1"]},
    {"name": "3spM1$string$1", "symbols": [{"literal":"h"}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3spM1", "symbols": ["3spM1$string$1"]},
    {"name": "3spM2$string$1", "symbols": [{"literal":"h"}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3spM2", "symbols": ["3spM2$string$1"]},
    {"name": "1ss", "symbols": [{"literal":"i"}]},
    {"name": "preposition_NI$string$2", "symbols": [{"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition_NI", "symbols": ["preposition_NI$string$2"]},
    {"name": "BE_3s_pres$string$1", "symbols": [{"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BE_3s_pres", "symbols": ["BE_3s_pres$string$1"]},
    {"name": "3ssI$string$1", "symbols": [{"literal":"i"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3ssI", "symbols": ["3ssI$string$1"]},
    {"name": "3soI$string$1", "symbols": [{"literal":"i"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3soI", "symbols": ["3soI$string$1"]},
    {"name": "3spI1$string$1", "symbols": [{"literal":"i"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3spI1", "symbols": ["3spI1$string$1"]},
    {"name": "3spI2$string$1", "symbols": [{"literal":"i"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3spI2", "symbols": ["3spI2$string$1"]},
    {"name": "3srI$string$1", "symbols": [{"literal":"i"}, {"literal":"t"}, {"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3srI", "symbols": ["3srI$string$1"]},
    {"name": "1so$string$1", "symbols": [{"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "1so", "symbols": ["1so$string$1"]},
    {"name": "1sp2$string$1", "symbols": [{"literal":"m"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "1sp2", "symbols": ["1sp2$string$1"]},
    {"name": "1sp1$string$1", "symbols": [{"literal":"m"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "1sp1", "symbols": ["1sp1$string$1"]},
    {"name": "1sr$string$1", "symbols": [{"literal":"m"}, {"literal":"y"}, {"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "1sr", "symbols": ["1sr$string$1"]},
    {"name": "NOT$string$1", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NOT", "symbols": ["NOT$string$1"]},
    {"name": "OF$string$1", "symbols": [{"literal":"o"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OF", "symbols": ["OF$string$1"]},
    {"name": "preposition_NI$string$3", "symbols": [{"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition_NI", "symbols": ["preposition_NI$string$3"]},
    {"name": "symmetrical_conjuntion$string$2", "symbols": [{"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "symmetrical_conjuntion", "symbols": ["symmetrical_conjuntion$string$2"]},
    {"name": "AN_noun_sI$string$3", "symbols": [{"literal":"o"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AN_noun_sI", "symbols": ["AN_noun_sI$string$3"]},
    {"name": "AN_color_adjective$string$1", "symbols": [{"literal":"o"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AN_color_adjective", "symbols": ["AN_color_adjective$string$1"]},
    {"name": "1pp1$string$1", "symbols": [{"literal":"o"}, {"literal":"u"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "1pp1", "symbols": ["1pp1$string$1"]},
    {"name": "1pp2$string$1", "symbols": [{"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "1pp2", "symbols": ["1pp2$string$1"]},
    {"name": "1pr$string$1", "symbols": [{"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"v"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "1pr", "symbols": ["1pr$string$1"]},
    {"name": "A_shape_adjective$string$1", "symbols": [{"literal":"r"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "A_shape_adjective", "symbols": ["A_shape_adjective$string$1"]},
    {"name": "3ssF$string$1", "symbols": [{"literal":"s"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3ssF", "symbols": ["3ssF$string$1"]},
    {"name": "A_physical_adjective$string$1", "symbols": [{"literal":"s"}, {"literal":"o"}, {"literal":"f"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "A_physical_adjective", "symbols": ["A_physical_adjective$string$1"]},
    {"name": "demonstrative_s$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "demonstrative_s", "symbols": ["demonstrative_s$string$1"]},
    {"name": "subclause_conjunction_P$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "subclause_conjunction_P", "symbols": ["subclause_conjunction_P$string$1"]},
    {"name": "THE$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "THE", "symbols": ["THE$string$1"]},
    {"name": "3spN1$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"i"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3spN1", "symbols": ["3spN1$string$1"]},
    {"name": "3pp1$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"i"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3pp1", "symbols": ["3pp1$string$1"]},
    {"name": "3spN2$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"i"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3spN2", "symbols": ["3spN2$string$1"]},
    {"name": "3pp2$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"i"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3pp2", "symbols": ["3pp2$string$1"]},
    {"name": "3soN$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3soN", "symbols": ["3soN$string$1"]},
    {"name": "3po$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3po", "symbols": ["3po$string$1"]},
    {"name": "3srN$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"m"}, {"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3srN", "symbols": ["3srN$string$1"]},
    {"name": "3pr$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"m"}, {"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"v"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3pr", "symbols": ["3pr$string$1"]},
    {"name": "demonstrative_p$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "demonstrative_p", "symbols": ["demonstrative_p$string$1"]},
    {"name": "3ssN$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3ssN", "symbols": ["3ssN$string$1"]},
    {"name": "3ps$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "3ps", "symbols": ["3ps$string$1"]},
    {"name": "demonstrative_s$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "demonstrative_s", "symbols": ["demonstrative_s$string$2"]},
    {"name": "demonstrative_p$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"o"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "demonstrative_p", "symbols": ["demonstrative_p$string$2"]},
    {"name": "TO$string$1", "symbols": [{"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TO", "symbols": ["TO$string$1"]},
    {"name": "preposition_VD$string$2", "symbols": [{"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition_VD", "symbols": ["preposition_VD$string$2"]},
    {"name": "1po$string$1", "symbols": [{"literal":"u"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "1po", "symbols": ["1po$string$1"]},
    {"name": "BE_1s_past$string$1", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BE_1s_past", "symbols": ["BE_1s_past$string$1"]},
    {"name": "BE_3s_past$string$1", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BE_3s_past", "symbols": ["BE_3s_past$string$1"]},
    {"name": "1ps$string$1", "symbols": [{"literal":"w"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "1ps", "symbols": ["1ps$string$1"]},
    {"name": "BE_1p_past$string$1", "symbols": [{"literal":"w"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BE_1p_past", "symbols": ["BE_1p_past$string$1"]},
    {"name": "BE_2s_past$string$1", "symbols": [{"literal":"w"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BE_2s_past", "symbols": ["BE_2s_past$string$1"]},
    {"name": "BE_2p_past$string$1", "symbols": [{"literal":"w"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BE_2p_past", "symbols": ["BE_2p_past$string$1"]},
    {"name": "BE_3p_past$string$1", "symbols": [{"literal":"w"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BE_3p_past", "symbols": ["BE_3p_past$string$1"]},
    {"name": "subclause_conjunction_P$string$2", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"i"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "subclause_conjunction_P", "symbols": ["subclause_conjunction_P$string$2"]},
    {"name": "WILL$string$1", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WILL", "symbols": ["WILL$string$1"]},
    {"name": "preposition_NI$string$4", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition_NI", "symbols": ["preposition_NI$string$4"]},
    {"name": "A_material_adjective$string$1", "symbols": [{"literal":"w"}, {"literal":"o"}, {"literal":"o"}, {"literal":"d"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "A_material_adjective", "symbols": ["A_material_adjective$string$1"]},
    {"name": "2ss$string$1", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "2ss", "symbols": ["2ss$string$1"]},
    {"name": "2so$string$1", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "2so", "symbols": ["2so$string$1"]},
    {"name": "2ps$string$1", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "2ps", "symbols": ["2ps$string$1"]},
    {"name": "2po$string$1", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "2po", "symbols": ["2po$string$1"]},
    {"name": "A_age_adjective$string$1", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "A_age_adjective", "symbols": ["A_age_adjective$string$1"]},
    {"name": "2sp1$string$1", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "2sp1", "symbols": ["2sp1$string$1"]},
    {"name": "2pp1$string$1", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "2pp1", "symbols": ["2pp1$string$1"]},
    {"name": "2sp2$string$1", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "2sp2", "symbols": ["2sp2$string$1"]},
    {"name": "2pp2$string$1", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "2pp2", "symbols": ["2pp2$string$1"]},
    {"name": "2sr$string$1", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "2sr", "symbols": ["2sr$string$1"]},
    {"name": "2pr$string$1", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"s"}, {"literal":"e"}, {"literal":"l"}, {"literal":"v"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "2pr", "symbols": ["2pr$string$1"]}
]
  , ParserStart: "text"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
