// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }

function clean(data) {
let cleaned = data;
for (let index = 0; index < data.length; index++) {
if (data[index] === null || data[index] === ' ') {
	cleaned.splice(index, 1);
}}
return cleaned;
}

function join(data) {
let joined = "";
for (let index = 0; index < data.length; index++) {
	joined += data[index];
}
return joined;
}

function id(data) {
return data[0];
}
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "coordinating_conjunction$string$1", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "coordinating_conjunction", "symbols": ["coordinating_conjunction$string$1"], "postprocess": (data)=>["coor.conj.",id(data)]},
    {"name": "coordinating_conjunction$string$2", "symbols": [{"literal":"b"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "coordinating_conjunction", "symbols": ["coordinating_conjunction$string$2"], "postprocess": (data)=>["coor.conj.",id(data)]},
    {"name": "coordinating_conjunction$string$3", "symbols": [{"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "coordinating_conjunction", "symbols": ["coordinating_conjunction$string$3"], "postprocess": (data)=>["coor.conj.",id(data)]},
    {"name": "subordinating_conjunction$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "subordinating_conjunction", "symbols": ["subordinating_conjunction$string$1"], "postprocess": (data) => ["sub.conj.",id(data)]},
    {"name": "copula$string$1", "symbols": [{"literal":"b"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$1"], "postprocess": (data)=>["copula",id(data)]},
    {"name": "copula$string$2", "symbols": [{"literal":"b"}, {"literal":"e"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$2"], "postprocess": (data)=>["copula",id(data)]},
    {"name": "copula$string$3", "symbols": [{"literal":"a"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$3"], "postprocess": (data)=>["copula",id(data)]},
    {"name": "copula$string$4", "symbols": [{"literal":"a"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$4"], "postprocess": (data)=>["copula",id(data)]},
    {"name": "copula$string$5", "symbols": [{"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$5"], "postprocess": (data)=>["copula",id(data)]},
    {"name": "copula$string$6", "symbols": [{"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$6"], "postprocess": (data)=>["copula",id(data)]},
    {"name": "copula$string$7", "symbols": [{"literal":"i"}, {"literal":"s"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$7"], "postprocess": (data)=>["copula",id(data)]},
    {"name": "copula$string$8", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$8"], "postprocess": (data) =>["copula",id(data)]},
    {"name": "copula$string$9", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"s"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$9"], "postprocess": (data)=>["copula",id(data)]},
    {"name": "copula$string$10", "symbols": [{"literal":"w"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$10"], "postprocess": (data)=>["copula",id(data)]},
    {"name": "copula$string$11", "symbols": [{"literal":"w"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$11"], "postprocess": (data)=>["copula",id(data)]},
    {"name": "determiner$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$1"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$2"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$3"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$4", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"o"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$4"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner", "symbols": [{"literal":"a"}], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$5", "symbols": [{"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$5"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$6", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$6"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$7", "symbols": [{"literal":"m"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$7"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$8", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$8"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$9", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$9"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$10", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"i"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$10"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$11", "symbols": [{"literal":"h"}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$11"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$12", "symbols": [{"literal":"i"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$12"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$13", "symbols": [{"literal":"o"}, {"literal":"u"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$13"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "AS$string$1", "symbols": [{"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AS", "symbols": ["AS$string$1"], "postprocess": (data)=>["AS",id(data)]},
    {"name": "DID$string$1", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DID", "symbols": ["DID$string$1"], "postprocess": (data)=>["DID",id(data)]},
    {"name": "DIDNT$string$1", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"d"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DIDNT", "symbols": ["DIDNT$string$1"], "postprocess": (data)=>["DIDNT",id(data)]},
    {"name": "DO$string$1", "symbols": [{"literal":"d"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO", "symbols": ["DO$string$1"], "postprocess": (data)=>["DO",id(data)]},
    {"name": "DO$string$2", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO", "symbols": ["DO$string$2"], "postprocess": (data)=>["DO",id(data)]},
    {"name": "DONT$string$1", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DONT", "symbols": ["DONT$string$1"], "postprocess": (data)=>["DONT",id(data)]},
    {"name": "DONT$string$2", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"e"}, {"literal":"s"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DONT", "symbols": ["DONT$string$2"], "postprocess": (data)=>["DONT",id(data)]},
    {"name": "NOT$string$1", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NOT", "symbols": ["NOT$string$1"], "postprocess": (data)=>["NOT",id(data)]},
    {"name": "OF$string$1", "symbols": [{"literal":"o"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OF", "symbols": ["OF$string$1"], "postprocess": (data)=>["OF",id(data)]},
    {"name": "TO$string$1", "symbols": [{"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TO", "symbols": ["TO$string$1"], "postprocess": (data)=>["TO",id(data)]},
    {"name": "WILL$string$1", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WILL", "symbols": ["WILL$string$1"], "postprocess": (data)=>["WILL",id(data)]},
    {"name": "WONT$string$1", "symbols": [{"literal":"w"}, {"literal":"o"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WONT", "symbols": ["WONT$string$1"], "postprocess": (data)=>["WONT",id(data)]},
    {"name": "WOULD$string$1", "symbols": [{"literal":"w"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WOULD", "symbols": ["WOULD$string$1"], "postprocess": (data)=>["WOULD",id(data)]},
    {"name": "WOULDNT$string$1", "symbols": [{"literal":"w"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "WOULDNT", "symbols": ["WOULDNT$string$1"], "postprocess": (data)=>["WOULDNT",id(data)]},
    {"name": "adverb$string$1", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$1"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "present_perfective$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "present_perfective", "symbols": ["present_perfective$string$1"], "postprocess": (data)=>["pres.perf.",id(data)]},
    {"name": "present_perfective$string$2", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "present_perfective", "symbols": ["present_perfective$string$2"], "postprocess": (data)=>["pres.perf.",id(data)]},
    {"name": "present_perfective$string$3", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "present_perfective", "symbols": ["present_perfective$string$3"], "postprocess": (data)=>["pres.perf.",id(data)]},
    {"name": "present_perfective$string$4", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"s"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "present_perfective", "symbols": ["present_perfective$string$4"], "postprocess": (data)=>["pres.perf.",id(data)]},
    {"name": "past_perfective$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "past_perfective", "symbols": ["past_perfective$string$1"], "postprocess": (data)=>["past-perf.",id(data)]},
    {"name": "past_perfective$string$2", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"d"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "past_perfective", "symbols": ["past_perfective$string$2"], "postprocess": (data) =>["past-perf.",id(data)]},
    {"name": "possessive$string$1", "symbols": [{"literal":"m"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "possessive", "symbols": ["possessive$string$1"], "postprocess": (data)=>["possessive",id(data)]},
    {"name": "possessive$string$2", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "possessive", "symbols": ["possessive$string$2"], "postprocess": (data)=>["possessive",id(data)]},
    {"name": "possessive$string$3", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "possessive", "symbols": ["possessive$string$3"], "postprocess": (data)=>["possessive",id(data)]},
    {"name": "possessive$string$4", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"i"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "possessive", "symbols": ["possessive$string$4"], "postprocess": (data)=>["possessive",id(data)]},
    {"name": "possessive$string$5", "symbols": [{"literal":"h"}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "possessive", "symbols": ["possessive$string$5"], "postprocess": (data)=>["possessive",id(data)]},
    {"name": "possessive$string$6", "symbols": [{"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "possessive", "symbols": ["possessive$string$6"], "postprocess": (data)=>["possessive",id(data)]},
    {"name": "preposition$string$1", "symbols": [{"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$1"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "preposition$string$2", "symbols": [{"literal":"b"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$2"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "preposition$string$3", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$3"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "preposition$string$4", "symbols": [{"literal":"f"}, {"literal":"r"}, {"literal":"o"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$4"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "preposition$string$5", "symbols": [{"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$5"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "preposition$string$6", "symbols": [{"literal":"o"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$6"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "preposition$string$7", "symbols": [{"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$7"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "preposition$string$8", "symbols": [{"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$8"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "preposition$string$9", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$9"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "pronoun$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$1"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$2"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$3"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$4", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"o"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$4"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$5", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$5"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "adverb$string$2", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$2"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "adjective$string$1", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$1"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "pronoun$string$6", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$6"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "adjective$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$2"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "adverb$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$3"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "pronoun", "symbols": [{"literal":"i"}], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$7", "symbols": [{"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$7"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$8", "symbols": [{"literal":"w"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$8"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$9", "symbols": [{"literal":"u"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$9"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$10", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$10"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$11", "symbols": [{"literal":"s"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$11"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$12", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$12"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$13", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$13"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$14", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$14"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$15", "symbols": [{"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$15"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$16", "symbols": [{"literal":"h"}, {"literal":"i"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$16"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$17", "symbols": [{"literal":"i"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$17"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "interrogative$string$1", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "interrogative", "symbols": ["interrogative$string$1"], "postprocess": (data)=>["interrogative",id(data)]},
    {"name": "pronoun$string$18", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$18"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "interrogative$string$2", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "interrogative", "symbols": ["interrogative$string$2"], "postprocess": (data)=>["interrogative",id(data)]},
    {"name": "pronoun$string$19", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$19"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "interrogative$string$3", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"i"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "interrogative", "symbols": ["interrogative$string$3"], "postprocess": (data)=>["interrogative",id(data)]},
    {"name": "pronoun$string$20", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"i"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$20"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "interrogative$string$4", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "interrogative", "symbols": ["interrogative$string$4"], "postprocess": (data)=>["interrogative",id(data)]},
    {"name": "pronoun$string$21", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$21"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "adverb$string$4", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$4"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "interrogative$string$5", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "interrogative", "symbols": ["interrogative$string$5"], "postprocess": (data)=>["interrogative",id(data)]},
    {"name": "pronoun$string$22", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$22"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "adverb$string$5", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$5"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "interrogative$string$6", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "interrogative", "symbols": ["interrogative$string$6"], "postprocess": (data)=>["interrogative",id(data)]},
    {"name": "pronoun$string$23", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$23"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "adverb$string$6", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$6"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "interrogative$string$7", "symbols": [{"literal":"h"}, {"literal":"o"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "interrogative", "symbols": ["interrogative$string$7"], "postprocess": (data)=>["interrogative",id(data)]},
    {"name": "pronoun$string$24", "symbols": [{"literal":"h"}, {"literal":"o"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$24"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "adverb$string$7", "symbols": [{"literal":"h"}, {"literal":"o"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$7"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "quantifier$string$1", "symbols": [{"literal":"a"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$1"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$2", "symbols": [{"literal":"m"}, {"literal":"o"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$2"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$3", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"n"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$3"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$4", "symbols": [{"literal":"s"}, {"literal":"o"}, {"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$4"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$5", "symbols": [{"literal":"f"}, {"literal":"e"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$5"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$6", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$6"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$7", "symbols": [{"literal":"z"}, {"literal":"e"}, {"literal":"r"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$7"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$8", "symbols": [{"literal":"o"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$8"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$9", "symbols": [{"literal":"t"}, {"literal":"w"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$9"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$10", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$10"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$11", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$11"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$12", "symbols": [{"literal":"f"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$12"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$13", "symbols": [{"literal":"s"}, {"literal":"i"}, {"literal":"x"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$13"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$14", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$14"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$15", "symbols": [{"literal":"e"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$15"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$16", "symbols": [{"literal":"n"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$16"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$17", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$17"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "preposition$string$10", "symbols": [{"literal":"a"}, {"literal":"b"}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$10"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "preposition$string$11", "symbols": [{"literal":"a"}, {"literal":"b"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$11"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "preposition$string$12", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"r"}, {"literal":"o"}, {"literal":"s"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$12"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "verb$string$1", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$1"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "copula$string$12", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$12"], "postprocess": (data)=>["copula",id(data)]},
    {"name": "noun$string$1", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$1"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$2", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$2"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$3", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$3"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$3", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$3"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "noun$string$2", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$2"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$3", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$3"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$4", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$4"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$4", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$4"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$5", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$5"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$6", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$6"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$4", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$4"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$7", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$7"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$8", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$8"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$5", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$5"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "noun$string$5", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"a"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$5"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$6", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"a"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$6"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "adjective$string$6", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$6"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "adverb$string$8", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$8"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "noun$string$7", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"i"}, {"literal":"s"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$7"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$8", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"i"}, {"literal":"s"}, {"literal":"m"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$8"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$9", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$9"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$10", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$10"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$11", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"i"}, {"literal":"t"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$11"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$12", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$12"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$9", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$9"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$10", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$10"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$7", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$7"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "noun$string$13", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$13"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$14", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$14"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$11", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$11"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$15", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$15"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "adjective$string$8", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$8"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "noun$string$16", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$16"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "adjective$string$9", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"a"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$9"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "adverb$string$9", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$9"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "noun$string$17", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$17"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$12", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$12"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$10", "symbols": [{"literal":"a"}, {"literal":"f"}, {"literal":"r"}, {"literal":"a"}, {"literal":"i"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$10"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "adverb$string$10", "symbols": [{"literal":"a"}, {"literal":"f"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$10"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "preposition$string$13", "symbols": [{"literal":"a"}, {"literal":"f"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$13"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "adverb$string$11", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$11"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "preposition$string$14", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$14"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "verb$string$13", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$13"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$18", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$18"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$14", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$14"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$11", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$11"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$15", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$15"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$19", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$19"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$16", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$16"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$20", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$20"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "adjective$string$12", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$12"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "postposition$string$1", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "postposition", "symbols": ["postposition$string$1"], "postprocess": (data)=>["postposition",id(data)]},
    {"name": "verb$string$17", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$17"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$13", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"a"}, {"literal":"b"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$13"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$18", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$18"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$19", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$19"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$14", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$14"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "noun$string$21", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$21"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$22", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$22"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "adjective$string$15", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$15"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$20", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$20"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$23", "symbols": [{"literal":"a"}, {"literal":"i"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$23"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$24", "symbols": [{"literal":"a"}, {"literal":"i"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$24"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "adjective$string$16", "symbols": [{"literal":"a"}, {"literal":"l"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$16"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "adverb$string$12", "symbols": [{"literal":"a"}, {"literal":"l"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$12"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "preposition$string$15", "symbols": [{"literal":"a"}, {"literal":"l"}, {"literal":"o"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$15"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "adverb$string$13", "symbols": [{"literal":"a"}, {"literal":"l"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"d"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$13"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "adverb$string$14", "symbols": [{"literal":"a"}, {"literal":"l"}, {"literal":"w"}, {"literal":"a"}, {"literal":"y"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$14"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "verb$string$21", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$21"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$25", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$25"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$22", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$22"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$23", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$23"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$24", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$24"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$26", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$26"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$25", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$25"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$27", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$27"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$26", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$26"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$17", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$17"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$27", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$27"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$18", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$18"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$28", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$28"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adverb$string$15", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"r"}, {"literal":"i"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$15"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "adjective$string$19", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$19"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "quantifier$string$18", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"o"}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$18"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "adjective$string$20", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$20"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "adverb$string$16", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"d"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$16"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "verb$string$29", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$29"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$30", "symbols": [{"literal":"d"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$30"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$28", "symbols": [{"literal":"d"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$28"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$29", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$29"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$30", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$30"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$31", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$31"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$32", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$32"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$31", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$31"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$33", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$33"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$21", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$21"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$34", "symbols": [{"literal":"g"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$34"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$35", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$35"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$32", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$32"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$36", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$36"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$22", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$22"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$37", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$37"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$33", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$33"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "adjective$string$23", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$23"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$38", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$38"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$34", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$34"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$39", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$39"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$40", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$40"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$24", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$24"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "noun$string$35", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$35"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$41", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$41"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$42", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"v"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$42"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$25", "symbols": [{"literal":"g"}, {"literal":"o"}, {"literal":"o"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$25"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$43", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$43"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$44", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$44"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$45", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$45"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$36", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$36"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$46", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$46"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$37", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$37"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$47", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$47"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$26", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"b"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$26"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$48", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$48"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$27", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$27"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "noun$string$38", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$38"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$39", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$39"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$49", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$49"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$40", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$40"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "adjective$string$28", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$28"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$50", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$50"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$41", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$41"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$42", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$42"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$43", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$43"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "adverb$string$17", "symbols": [{"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$17"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "adverb$string$18", "symbols": [{"literal":"w"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$18"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "exclamation$string$1", "symbols": [{"literal":"w"}, {"literal":"o"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "exclamation", "symbols": ["exclamation$string$1"], "postprocess": (data)=>["exclamation",id(data)]},
    {"name": "text", "symbols": ["sentence"], "postprocess": (data) => ["text", id(data)]},
    {"name": "sentence", "symbols": ["statement"], "postprocess": (data) => ["sentence", id(data)]},
    {"name": "sentence", "symbols": ["question"], "postprocess": (data) => ["sentence", id(data)]},
    {"name": "sentence", "symbols": ["command"], "postprocess": (data) => ["sentence", id(data)]},
    {"name": "sentence", "symbols": ["exclamatory"], "postprocess": (data) => ["sentence", id(data)]},
    {"name": "statement", "symbols": ["head", "_", "tail"], "postprocess": (data) => ["statement", clean(data)]},
    {"name": "statement", "symbols": ["statement", "_", "coordinating_conjunction", "_", "statement"], "postprocess": (data) => ["statement", clean(data)]},
    {"name": "question", "symbols": ["copula_core", "_", "nominal_phrase"], "postprocess": (data) => ["question", clean(data)]},
    {"name": "question", "symbols": ["interrogative", "_", "copula_core", "_", "nominal_phrase"], "postprocess": (data) => ["question", clean(data)]},
    {"name": "question", "symbols": ["DO", "_", "nominal_phrase", "_", "tail"], "postprocess": (data) => ["question", clean(data)]},
    {"name": "question", "symbols": ["DID", "_", "nominal_phrase", "_", "tail"], "postprocess": (data) => ["question", clean(data)]},
    {"name": "question", "symbols": ["interrogative", "_", "DO", "_", "nominal_phrase", "_", "tail"], "postprocess": (data) => ["question", clean(data)]},
    {"name": "question", "symbols": ["interrogative", "_", "DID", "_", "nominal_phrase", "_", "tail"], "postprocess": (data) => ["question", clean(data)]},
    {"name": "question", "symbols": ["copula_core", "_", "nominal_phrase", "_", "copula_arguments"], "postprocess": (data) => ["question", clean(data)]},
    {"name": "question", "symbols": ["interrogative", "_", "copula_core", "_", "nominal_phrase"], "postprocess": (data) => ["question", clean(data)]},
    {"name": "command", "symbols": ["tail"], "postprocess": (data) => ["command", clean(data)]},
    {"name": "exclamatory", "symbols": ["exclamation"], "postprocess": (data) => ["exclamatory", clean(data)]},
    {"name": "head", "symbols": ["nominal_phrase"], "postprocess": (data) => ["head", id(data)]},
    {"name": "head", "symbols": ["head", "_", "coordinating_conjunction", "_", "head"], "postprocess": (data) => ["head", clean(data)]},
    {"name": "tail", "symbols": ["tail_core"], "postprocess": (data) => ["tail", id(data)]},
    {"name": "tail", "symbols": ["tail_core", "_", "end_phrases"], "postprocess": (data) => ["tail", clean(data)]},
    {"name": "tail_core", "symbols": ["verb_phrase"], "postprocess": (data) => ["tail_core", id(data)]},
    {"name": "tail_core", "symbols": ["verb_phrase", "_", "arguments"], "postprocess": (data) => ["tail_core", clean(data)]},
    {"name": "tail_core", "symbols": ["copula_core"], "postprocess": (data) => ["tail_core", id(data)]},
    {"name": "tail_core", "symbols": ["copula_core", "_", "copula_arguments"], "postprocess": (data) => ["tail_core", clean(data)]},
    {"name": "tail_core", "symbols": ["tail", "_", "coordinating_conjunction", "_", "tail"], "postprocess": (data) => ["tail_core", clean(data)]},
    {"name": "copula_arguments", "symbols": ["adjective_phrase"], "postprocess": (data) => ["copula arguments", id(data)]},
    {"name": "copula_arguments", "symbols": ["adjectival_AS_phrase"], "postprocess": (data) => ["copula arguments", id(data)]},
    {"name": "copula_arguments", "symbols": ["nominal_phrase"], "postprocess": (data) => ["copula arguments", id(data)]},
    {"name": "copula_arguments", "symbols": ["prepositional_phrase"], "postprocess": (data) => ["copula arguments", id(data)]},
    {"name": "arguments", "symbols": ["nominal_phrase"], "postprocess": (data) => ["arguments", id(data)]},
    {"name": "arguments", "symbols": ["nominal_phrase", "_", "nominal_phrase"], "postprocess": (data) => ["arguments", clean(data)]},
    {"name": "arguments", "symbols": ["nominal_phrase", "_", "nominal_phrase", "_", "nominal_phrase"], "postprocess": (data) => ["arguments", clean(data)]},
    {"name": "end_phrases", "symbols": ["end_phrase"], "postprocess": (data) => ["end phrases", id(data)]},
    {"name": "end_phrases", "symbols": ["end_phrase", "_", "end_phrases"], "postprocess": (data) => ["end phrases", clean(data)]},
    {"name": "end_phrase", "symbols": ["adverb_phrase"], "postprocess": (data) => ["end phrase", id(data)]},
    {"name": "end_phrase", "symbols": ["prepositional_phrase"], "postprocess": (data) => ["end phrase", id(data)]},
    {"name": "property_subclause", "symbols": ["statement"], "postprocess": (data) => ["property subclause", id(data)]},
    {"name": "property_subclause", "symbols": ["tail"], "postprocess": (data) => ["property subclause", id(data)]},
    {"name": "property_subclause", "symbols": ["subordinating_conjunction", "_", "statement"], "postprocess": (data) => ["property subclause", clean(data)]},
    {"name": "property_subclause", "symbols": ["subordinating_conjunction", "_", "tail"], "postprocess": (data) => ["property subclause", clean(data)]},
    {"name": "property_subclause", "symbols": ["interrogative", "_", "statement"], "postprocess": (data) => ["property subclause", clean(data)]},
    {"name": "property_subclause", "symbols": ["interrogative", "_", "tail"], "postprocess": (data) => ["property subclause", clean(data)]},
    {"name": "property_subclause", "symbols": ["property_subclause", "_", "prepositional_phrase"], "postprocess": (data) => ["property subclause", clean(data)]},
    {"name": "property_subclause", "symbols": ["property_subclause", "_", "coordinating_conjunction", "_", "property_subclause"], "postprocess": (data) => ["property subclause", clean(data)]},
    {"name": "nominal_subclause", "symbols": ["tail"], "postprocess": (data) => ["nominal subclause", id(data)]},
    {"name": "nominal_subclause", "symbols": ["subordinating_conjunction", "_", "statement"], "postprocess": (data) => ["nominal subclause", clean(data)]},
    {"name": "nominal_subclause", "symbols": ["subordinating_conjunction", "_", "tail"], "postprocess": (data) => ["nominal subclause", clean(data)]},
    {"name": "nominal_subclause", "symbols": ["interrogative", "_", "statement"], "postprocess": (data) => ["nominal subclause", clean(data)]},
    {"name": "nominal_subclause", "symbols": ["interrogative", "_", "tail"], "postprocess": (data) => ["nominal subclause", clean(data)]},
    {"name": "adverbial_subclause", "symbols": ["tail"], "postprocess": (data) => ["adverbial subclause", id(data)]},
    {"name": "adjectival_AS_phrase", "symbols": ["AS", "_", "adjective_phrase", "_", "AS", "_", "nominal_phrase"], "postprocess": (data) => ["AS phrase", clean(data)]},
    {"name": "nominal_phrase", "symbols": ["pronoun"], "postprocess": (data) => ["nominal phrase", id(data)]},
    {"name": "nominal_phrase", "symbols": ["possessive"], "postprocess": (data) => ["nominal phrase", id(data)]},
    {"name": "nominal_phrase", "symbols": ["noun_phrase"], "postprocess": (data) => ["nominal phrase", id(data)]},
    {"name": "nominal_phrase", "symbols": ["noun_phrase", "_", "prepositional_phrase"], "postprocess": (data) => ["nominal phrase", clean(data)]},
    {"name": "nominal_phrase", "symbols": ["noun_phrase", "_", "property_subclause"], "postprocess": (data) => ["nominal phrase", clean(data)]},
    {"name": "nominal_phrase", "symbols": ["nominal_phrase", "_", "coordinating_conjunction", "_", "nominal_phrase"], "postprocess": (data) => ["nominal phrase", clean(data)]},
    {"name": "noun_phrase", "symbols": ["noun"], "postprocess": (data) => ["noun phrase", id(data)]},
    {"name": "noun_phrase", "symbols": ["nominal_subclause"], "postprocess": (data) => ["noun phrase", id(data)]},
    {"name": "noun_phrase", "symbols": ["adjective_phrase", "_", "noun"], "postprocess": (data) => ["noun phrase", clean(data)]},
    {"name": "noun_phrase", "symbols": ["determiner", "_", "noun"], "postprocess": (data) => ["noun phrase", clean(data)]},
    {"name": "noun_phrase", "symbols": ["determiner", "_", "adjective_phrase", "_", "noun"], "postprocess": (data) => ["noun phrase", clean(data)]},
    {"name": "verbal", "symbols": ["verb"], "postprocess": (data) => ["verbal", id(data)]},
    {"name": "verbal", "symbols": ["adverb_phrase", "_", "verb"], "postprocess": (data) => ["nominal phrase", clean(data)]},
    {"name": "verb_phrase", "symbols": ["verbal"], "postprocess": (data) => ["verb phrase", id(data)]},
    {"name": "verb_phrase", "symbols": ["DO", "_", "NOT", "_", "verbal"], "postprocess": (data) => ["verb phrase", clean(data)]},
    {"name": "verb_phrase", "symbols": ["DONT", "_", "verbal"], "postprocess": (data) => ["verb phrase", clean(data)]},
    {"name": "verb_phrase", "symbols": ["DID", "_", "NOT", "_", "verbal"], "postprocess": (data) => ["verb phrase", clean(data)]},
    {"name": "verb_phrase", "symbols": ["DIDNT", "_", "verbal"], "postprocess": (data) => ["verb phrase", clean(data)]},
    {"name": "verb_phrase", "symbols": ["WILL", "_", "verbal"], "postprocess": (data) => ["verb phrase", clean(data)]},
    {"name": "verb_phrase", "symbols": ["WILL", "_", "NOT", "_", "verbal"], "postprocess": (data) => ["verb phrase", clean(data)]},
    {"name": "verb_phrase", "symbols": ["WONT", "_", "verbal"], "postprocess": (data) => ["verb phrase", clean(data)]},
    {"name": "verb_phrase", "symbols": ["WILL", "_", "present_perfective", "_", "verbal"], "postprocess": (data) => ["verb phrase", clean(data)]},
    {"name": "verb_phrase", "symbols": ["WILL", "_", "NOT", "_", "present_perfective", "_", "verbal"], "postprocess": (data) => ["verb phrase", clean(data)]},
    {"name": "verb_phrase", "symbols": ["WONT", "_", "present_perfective", "_", "verbal"], "postprocess": (data) => ["verb phrase", clean(data)]},
    {"name": "verb_phrase", "symbols": ["WOULD", "_", "verbal"], "postprocess": (data) => ["verb phrase", clean(data)]},
    {"name": "verb_phrase", "symbols": ["WOULD", "_", "NOT", "_", "verbal"], "postprocess": (data) => ["verb phrase", clean(data)]},
    {"name": "verb_phrase", "symbols": ["WOULDNT", "_", "verbal"], "postprocess": (data) => ["verb phrase", clean(data)]},
    {"name": "verb_phrase", "symbols": ["WOULD", "_", "present_perfective", "_", "verbal"], "postprocess": (data) => ["verb phrase", clean(data)]},
    {"name": "verb_phrase", "symbols": ["WOULD", "_", "NOT", "_", "present_perfective", "_", "verbal"], "postprocess": (data) => ["verb phrase", clean(data)]},
    {"name": "verb_phrase", "symbols": ["WOULDNT", "_", "present_perfective", "_", "verbal"], "postprocess": (data) => ["verb phrase", clean(data)]},
    {"name": "verb_phrase", "symbols": ["present_perfective", "_", "verbal"], "postprocess": (data) => ["verb phrase", clean(data)]},
    {"name": "verb_phrase", "symbols": ["adverb_phrase", "_", "present_perfective", "_", "verbal"], "postprocess": (data) => ["verb phrase", clean(data)]},
    {"name": "verb_phrase", "symbols": ["past_perfective", "_", "verbal"], "postprocess": (data) => ["verb phrase", clean(data)]},
    {"name": "verb_phrase", "symbols": ["adverb_phrase", "_", "past_perfective", "_", "verbal"], "postprocess": (data) => ["verb phrase", clean(data)]},
    {"name": "verb_phrase", "symbols": ["copula_core", "_", "verbal"], "postprocess": (data) => ["verb phrase", clean(data)]},
    {"name": "verb_phrase", "symbols": ["adverb_phrase", "_", "verbal"], "postprocess": (data) => ["verb phrase", clean(data)]},
    {"name": "verb_phrase", "symbols": ["verbal", "_", "coordinating_conjunction", "_", "verbal"], "postprocess": (data) => ["verb phrase", clean(data)]},
    {"name": "copula_core", "symbols": ["copula"], "postprocess": (data) => ["copula core", id(data)]},
    {"name": "copula_core", "symbols": ["copula", "_", "NOT"], "postprocess": (data) => ["copula core", clean(data)]},
    {"name": "copula_core", "symbols": ["WILL", "_", "copula"], "postprocess": (data) => ["copula core", clean(data)]},
    {"name": "copula_core", "symbols": ["WILL", "_", "NOT", "_", "copula"], "postprocess": (data) => ["copula core", clean(data)]},
    {"name": "copula_core", "symbols": ["WILL", "_", "present_perfective", "_", "copula"], "postprocess": (data) => ["copula core", clean(data)]},
    {"name": "copula_core", "symbols": ["WILL", "_", "NOT", "_", "present_perfective", "_", "copula"], "postprocess": (data) => ["copula core", clean(data)]},
    {"name": "copula_core", "symbols": ["WOULD", "_", "copula"], "postprocess": (data) => ["copula core", clean(data)]},
    {"name": "copula_core", "symbols": ["WOULD", "_", "NOT", "_", "copula"], "postprocess": (data) => ["copula core", clean(data)]},
    {"name": "copula_core", "symbols": ["WOULD", "_", "present_perfective", "_", "copula"], "postprocess": (data) => ["copula core", clean(data)]},
    {"name": "copula_core", "symbols": ["WOULD", "_", "NOT", "_", "present_perfective", "_", "copula"], "postprocess": (data) => ["copula core", clean(data)]},
    {"name": "copula_core", "symbols": ["present_perfective", "_", "copula"], "postprocess": (data) => ["copula core", clean(data)]},
    {"name": "copula_core", "symbols": ["present_perfective", "_", "NOT", "_", "copula"], "postprocess": (data) => ["copula core", clean(data)]},
    {"name": "copula_core", "symbols": ["past_perfective", "_", "copula"], "postprocess": (data) => ["copula core", clean(data)]},
    {"name": "copula_core", "symbols": ["past_perfective", "_", "NOT", "_", "copula"], "postprocess": (data) => ["copula core", clean(data)]},
    {"name": "adjective_phrase", "symbols": ["adjective"], "postprocess": (data) => ["adjective phrase", id(data)]},
    {"name": "adjective_phrase", "symbols": ["adverb_phrase", "_", "adjective"], "postprocess": (data) => ["adjective phrase", clean(data)]},
    {"name": "adjective_phrase", "symbols": ["adjective_phrase", "_", "adjective_phrase"], "postprocess": (data) => ["adjective phrase", clean(data)]},
    {"name": "adjective_phrase", "symbols": ["adjective_phrase", "_", "coordinating_conjunction", "_", "adjective_phrase"], "postprocess": (data) => ["adjective phrase", clean(data)]},
    {"name": "adverb_phrase", "symbols": ["adverb"], "postprocess": (data) => ["adverb phrase", id(data)]},
    {"name": "adverb_phrase", "symbols": ["adverb_phrase", "_", "adverb"], "postprocess": (data) => ["adverb phrase", clean(data)]},
    {"name": "prepositional_phrases", "symbols": ["prepositional_phrase"], "postprocess": (data) => ["prepositional phrases", id(data)]},
    {"name": "prepositional_phrases", "symbols": ["prepositional_phrase", "_", "prepositional_phrases"], "postprocess": (data) => ["prepositional phrases", clean(data)]},
    {"name": "prepositional_phrase", "symbols": ["preposition"], "postprocess": (data) => ["prepositional phrase", id(data)]},
    {"name": "prepositional_phrase", "symbols": ["preposition", "_", "nominal_phrase"], "postprocess": (data) => ["prepositional phrase", clean(data)]},
    {"name": "prepositional_phrase", "symbols": ["nominal_phrase", "_", "postposition"], "postprocess": (data) => ["prepositional phrase", clean(data)]},
    {"name": "prepositional_phrase", "symbols": ["prepositional_phrase", "_", "coordinating_conjunction", "_", "prepositional_phrase"], "postprocess": (data) => ["prepositional phrase", clean(data)]},
    {"name": "determiner", "symbols": ["quantifier_phrase"], "postprocess": (data) => ["determiner", id(data)]},
    {"name": "determiner", "symbols": ["quantifier_phrase", "_", "determiner"], "postprocess": (data) => ["determiner", clean(data)]},
    {"name": "determiner", "symbols": ["determiner", "_", "quantifier_phrase"], "postprocess": (data) => ["determiner", clean(data)]},
    {"name": "noun", "symbols": ["quantifier"], "postprocess": (data) => ["noun", id(data)]},
    {"name": "quantifier_phrase", "symbols": ["quantifier"], "postprocess": (data) => ["quantifier phrase", id(data)]},
    {"name": "quantifier_phrase", "symbols": ["quantifier", "_", "OF"], "postprocess": (data) => ["quantifier phrase", clean(data)]},
    {"name": "_", "symbols": [{"literal":" "}], "postprocess": id}
]
  , ParserStart: "text"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
