// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }

function clean(data) {
let cleaned = data;
for (let index = 0; index < data.length; index++) {
if (data[index] === null || data[index] === ' ') {
	cleaned.splice(index, 1);
}}
return cleaned;
}

function join(data) {
let joined = "";
for (let index = 0; index < data.length; index++) {
	joined += data[index];
}
return joined;
}

function id(data) {
return data[0];
}
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "coordinating_conjunction$string$1", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "coordinating_conjunction", "symbols": ["coordinating_conjunction$string$1"], "postprocess": (data)=>["coor.conj.",id(data)]},
    {"name": "coordinating_conjunction$string$2", "symbols": [{"literal":"b"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "coordinating_conjunction", "symbols": ["coordinating_conjunction$string$2"], "postprocess": (data)=>["coor.conj.",id(data)]},
    {"name": "coordinating_conjunction$string$3", "symbols": [{"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "coordinating_conjunction", "symbols": ["coordinating_conjunction$string$3"], "postprocess": (data)=>["coor.conj.",id(data)]},
    {"name": "subordinating_conjunction$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "subordinating_conjunction", "symbols": ["subordinating_conjunction$string$1"], "postprocess": (data) => ["sub.conj.",id(data)]},
    {"name": "copula$string$1", "symbols": [{"literal":"b"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$1"], "postprocess": (data)=>["copula",id(data)]},
    {"name": "copula$string$2", "symbols": [{"literal":"b"}, {"literal":"e"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$2"], "postprocess": (data)=>["copula",id(data)]},
    {"name": "copula$string$3", "symbols": [{"literal":"a"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$3"], "postprocess": (data)=>["copula",id(data)]},
    {"name": "copula$string$4", "symbols": [{"literal":"a"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$4"], "postprocess": (data)=>["copula",id(data)]},
    {"name": "copula$string$5", "symbols": [{"literal":"a"}, {"literal":"r"}, {"literal":"e"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$5"], "postprocess": (data)=>["copula",id(data)]},
    {"name": "copula$string$6", "symbols": [{"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$6"], "postprocess": (data)=>["copula",id(data)]},
    {"name": "copula$string$7", "symbols": [{"literal":"i"}, {"literal":"s"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$7"], "postprocess": (data)=>["copula",id(data)]},
    {"name": "copula$string$8", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$8"], "postprocess": (data) =>["copula",id(data)]},
    {"name": "copula$string$9", "symbols": [{"literal":"w"}, {"literal":"a"}, {"literal":"s"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$9"], "postprocess": (data)=>["copula",id(data)]},
    {"name": "copula$string$10", "symbols": [{"literal":"w"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$10"], "postprocess": (data)=>["copula",id(data)]},
    {"name": "copula$string$11", "symbols": [{"literal":"w"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$11"], "postprocess": (data)=>["copula",id(data)]},
    {"name": "determiner$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$1"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$2"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$3"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$4", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"o"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$4"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner", "symbols": [{"literal":"a"}], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$5", "symbols": [{"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$5"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$6", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$6"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$7", "symbols": [{"literal":"m"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$7"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$8", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$8"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$9", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$9"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$10", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"i"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$10"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$11", "symbols": [{"literal":"h"}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$11"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$12", "symbols": [{"literal":"i"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$12"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "determiner$string$13", "symbols": [{"literal":"o"}, {"literal":"u"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "determiner", "symbols": ["determiner$string$13"], "postprocess": (data)=>["determiner",id(data)]},
    {"name": "AS$string$1", "symbols": [{"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AS", "symbols": ["AS$string$1"], "postprocess": (data)=>["AS",id(data)]},
    {"name": "NOT$string$1", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "NOT", "symbols": ["NOT$string$1"], "postprocess": (data)=>["NOT",id(data)]},
    {"name": "OF$string$1", "symbols": [{"literal":"o"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OF", "symbols": ["OF$string$1"], "postprocess": (data)=>["OF",id(data)]},
    {"name": "TO$string$1", "symbols": [{"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TO", "symbols": ["TO$string$1"], "postprocess": (data)=>["TO",id(data)]},
    {"name": "DO$string$1", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO", "symbols": ["DO$string$1"], "postprocess": (data)=>["DO",id(data)]},
    {"name": "DO$string$2", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"d"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO", "symbols": ["DO$string$2"], "postprocess": (data)=>["DO",id(data)]},
    {"name": "DO$string$3", "symbols": [{"literal":"d"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO", "symbols": ["DO$string$3"], "postprocess": (data)=>["DO",id(data)]},
    {"name": "DO$string$4", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO", "symbols": ["DO$string$4"], "postprocess": (data)=>["DO",id(data)]},
    {"name": "DO$string$5", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO", "symbols": ["DO$string$5"], "postprocess": (data)=>["DO",id(data)]},
    {"name": "DO$string$6", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"e"}, {"literal":"s"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "DO", "symbols": ["DO$string$6"], "postprocess": (data)=>["DO",id(data)]},
    {"name": "aux_verb$string$1", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aux_verb", "symbols": ["aux_verb$string$1"], "postprocess": (data)=>["aux.verb",id(data)]},
    {"name": "aux_verb$string$2", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"d"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aux_verb", "symbols": ["aux_verb$string$2"], "postprocess": (data)=>["aux.verb",id(data)]},
    {"name": "aux_verb$string$3", "symbols": [{"literal":"d"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aux_verb", "symbols": ["aux_verb$string$3"], "postprocess": (data)=>["aux.verb",id(data)]},
    {"name": "aux_verb$string$4", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aux_verb", "symbols": ["aux_verb$string$4"], "postprocess": (data)=>["aux.verb",id(data)]},
    {"name": "aux_verb$string$5", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aux_verb", "symbols": ["aux_verb$string$5"], "postprocess": (data)=>["aux.verb",id(data)]},
    {"name": "aux_verb$string$6", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"e"}, {"literal":"s"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aux_verb", "symbols": ["aux_verb$string$6"], "postprocess": (data)=>["aux.verb",id(data)]},
    {"name": "aux_verb$string$7", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aux_verb", "symbols": ["aux_verb$string$7"], "postprocess": (data)=>["aux.verb",id(data)]},
    {"name": "aux_verb$string$8", "symbols": [{"literal":"w"}, {"literal":"o"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aux_verb", "symbols": ["aux_verb$string$8"], "postprocess": (data)=>["aux.verb",id(data)]},
    {"name": "aux_verb$string$9", "symbols": [{"literal":"w"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aux_verb", "symbols": ["aux_verb$string$9"], "postprocess": (data)=>["aux.verb",id(data)]},
    {"name": "aux_verb$string$10", "symbols": [{"literal":"w"}, {"literal":"o"}, {"literal":"u"}, {"literal":"l"}, {"literal":"d"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "aux_verb", "symbols": ["aux_verb$string$10"], "postprocess": (data)=>["aux.verb",id(data)]},
    {"name": "adverb$string$1", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$1"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "perfective$string$1", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "perfective", "symbols": ["perfective$string$1"], "postprocess": (data)=>["perfective.",id(data)]},
    {"name": "perfective$string$2", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "perfective", "symbols": ["perfective$string$2"], "postprocess": (data)=>["perfective",id(data)]},
    {"name": "perfective$string$3", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "perfective", "symbols": ["perfective$string$3"], "postprocess": (data)=>["perfective",id(data)]},
    {"name": "perfective$string$4", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"s"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "perfective", "symbols": ["perfective$string$4"], "postprocess": (data)=>["perfective",id(data)]},
    {"name": "perfective$string$5", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "perfective", "symbols": ["perfective$string$5"], "postprocess": (data)=>["perfective",id(data)]},
    {"name": "perfective$string$6", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"d"}, {"literal":"n"}, {"literal":"'"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "perfective", "symbols": ["perfective$string$6"], "postprocess": (data) =>["perfective",id(data)]},
    {"name": "possessive$string$1", "symbols": [{"literal":"m"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "possessive", "symbols": ["possessive$string$1"], "postprocess": (data)=>["possessive",id(data)]},
    {"name": "possessive$string$2", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "possessive", "symbols": ["possessive$string$2"], "postprocess": (data)=>["possessive",id(data)]},
    {"name": "possessive$string$3", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "possessive", "symbols": ["possessive$string$3"], "postprocess": (data)=>["possessive",id(data)]},
    {"name": "possessive$string$4", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"i"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "possessive", "symbols": ["possessive$string$4"], "postprocess": (data)=>["possessive",id(data)]},
    {"name": "possessive$string$5", "symbols": [{"literal":"h"}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "possessive", "symbols": ["possessive$string$5"], "postprocess": (data)=>["possessive",id(data)]},
    {"name": "possessive$string$6", "symbols": [{"literal":"o"}, {"literal":"u"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "possessive", "symbols": ["possessive$string$6"], "postprocess": (data)=>["possessive",id(data)]},
    {"name": "preposition$string$1", "symbols": [{"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$1"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "preposition$string$2", "symbols": [{"literal":"b"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$2"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "preposition$string$3", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$3"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "preposition$string$4", "symbols": [{"literal":"f"}, {"literal":"r"}, {"literal":"o"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$4"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "preposition$string$5", "symbols": [{"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$5"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "preposition$string$6", "symbols": [{"literal":"o"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$6"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "preposition$string$7", "symbols": [{"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$7"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "preposition$string$8", "symbols": [{"literal":"t"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$8"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "preposition$string$9", "symbols": [{"literal":"w"}, {"literal":"i"}, {"literal":"t"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$9"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "pronoun$string$1", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$1"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$2"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$3"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$4", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"o"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$4"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$5", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$5"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "adverb$string$2", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$2"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "adjective$string$1", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$1"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "pronoun$string$6", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$6"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "adjective$string$2", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$2"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "adverb$string$3", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$3"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "pronoun", "symbols": [{"literal":"i"}], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$7", "symbols": [{"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$7"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$8", "symbols": [{"literal":"w"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$8"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$9", "symbols": [{"literal":"u"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$9"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$10", "symbols": [{"literal":"y"}, {"literal":"o"}, {"literal":"u"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$10"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$11", "symbols": [{"literal":"s"}, {"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$11"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$12", "symbols": [{"literal":"h"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$12"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$13", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$13"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$14", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$14"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$15", "symbols": [{"literal":"h"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$15"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$16", "symbols": [{"literal":"h"}, {"literal":"i"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$16"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "pronoun$string$17", "symbols": [{"literal":"i"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$17"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "interrogative$string$1", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "interrogative", "symbols": ["interrogative$string$1"], "postprocess": (data)=>["interrogative",id(data)]},
    {"name": "pronoun$string$18", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$18"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "interrogative$string$2", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "interrogative", "symbols": ["interrogative$string$2"], "postprocess": (data)=>["interrogative",id(data)]},
    {"name": "pronoun$string$19", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$19"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "interrogative$string$3", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"i"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "interrogative", "symbols": ["interrogative$string$3"], "postprocess": (data)=>["interrogative",id(data)]},
    {"name": "pronoun$string$20", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"i"}, {"literal":"c"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$20"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "interrogative$string$4", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "interrogative", "symbols": ["interrogative$string$4"], "postprocess": (data)=>["interrogative",id(data)]},
    {"name": "pronoun$string$21", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$21"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "adverb$string$4", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$4"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "interrogative$string$5", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "interrogative", "symbols": ["interrogative$string$5"], "postprocess": (data)=>["interrogative",id(data)]},
    {"name": "pronoun$string$22", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$22"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "adverb$string$5", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$5"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "interrogative$string$6", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "interrogative", "symbols": ["interrogative$string$6"], "postprocess": (data)=>["interrogative",id(data)]},
    {"name": "pronoun$string$23", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$23"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "adverb$string$6", "symbols": [{"literal":"w"}, {"literal":"h"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$6"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "interrogative$string$7", "symbols": [{"literal":"h"}, {"literal":"o"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "interrogative", "symbols": ["interrogative$string$7"], "postprocess": (data)=>["interrogative",id(data)]},
    {"name": "pronoun$string$24", "symbols": [{"literal":"h"}, {"literal":"o"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pronoun", "symbols": ["pronoun$string$24"], "postprocess": (data)=>["pronoun",id(data)]},
    {"name": "adverb$string$7", "symbols": [{"literal":"h"}, {"literal":"o"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$7"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "quantifier$string$1", "symbols": [{"literal":"a"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$1"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$2", "symbols": [{"literal":"m"}, {"literal":"o"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$2"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$3", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"n"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$3"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$4", "symbols": [{"literal":"s"}, {"literal":"o"}, {"literal":"m"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$4"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$5", "symbols": [{"literal":"f"}, {"literal":"e"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$5"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$6", "symbols": [{"literal":"n"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$6"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$7", "symbols": [{"literal":"z"}, {"literal":"e"}, {"literal":"r"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$7"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$8", "symbols": [{"literal":"o"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$8"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$9", "symbols": [{"literal":"t"}, {"literal":"w"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$9"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$10", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$10"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$11", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"u"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$11"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$12", "symbols": [{"literal":"f"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$12"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$13", "symbols": [{"literal":"s"}, {"literal":"i"}, {"literal":"x"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$13"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$14", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$14"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$15", "symbols": [{"literal":"e"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$15"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$16", "symbols": [{"literal":"n"}, {"literal":"i"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$16"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "quantifier$string$17", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$17"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "preposition$string$10", "symbols": [{"literal":"a"}, {"literal":"b"}, {"literal":"o"}, {"literal":"u"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$10"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "preposition$string$11", "symbols": [{"literal":"a"}, {"literal":"b"}, {"literal":"o"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$11"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "preposition$string$12", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"r"}, {"literal":"o"}, {"literal":"s"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$12"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "verb$string$1", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$1"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "copula$string$12", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "copula", "symbols": ["copula$string$12"], "postprocess": (data)=>["copula",id(data)]},
    {"name": "noun$string$1", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$1"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$2", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$2"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$3", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$3"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$3", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$3"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "noun$string$2", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$2"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$3", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$3"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$4", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$4"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$4", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$4"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$5", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$5"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$6", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$6"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$4", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$4"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$7", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$7"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$8", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$8"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$5", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$5"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "noun$string$5", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"a"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$5"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$6", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"a"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$6"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "adjective$string$6", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$6"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "adverb$string$8", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$8"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "noun$string$7", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"i"}, {"literal":"s"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$7"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$8", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"i"}, {"literal":"s"}, {"literal":"m"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$8"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$9", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$9"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$10", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$10"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$11", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"i"}, {"literal":"t"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$11"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$12", "symbols": [{"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"v"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$12"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$9", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$9"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$10", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$10"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$7", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$7"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "noun$string$13", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$13"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$14", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$14"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$11", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$11"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$15", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$15"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "adjective$string$8", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$8"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "noun$string$16", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$16"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "adjective$string$9", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"a"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$9"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "adverb$string$9", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"a"}, {"literal":"l"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$9"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "noun$string$17", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"i"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$17"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$12", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$12"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$10", "symbols": [{"literal":"a"}, {"literal":"f"}, {"literal":"r"}, {"literal":"a"}, {"literal":"i"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$10"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "adverb$string$10", "symbols": [{"literal":"a"}, {"literal":"f"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$10"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "preposition$string$13", "symbols": [{"literal":"a"}, {"literal":"f"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$13"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "adverb$string$11", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$11"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "preposition$string$14", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$14"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "verb$string$13", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$13"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$18", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$18"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$14", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$14"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$11", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$11"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$15", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$15"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$19", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$19"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$16", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$16"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$20", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$20"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "adjective$string$12", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$12"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "postposition$string$1", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "postposition", "symbols": ["postposition$string$1"], "postprocess": (data)=>["postposition",id(data)]},
    {"name": "verb$string$17", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$17"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$13", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"a"}, {"literal":"b"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$13"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$18", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$18"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$19", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$19"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$14", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$14"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "noun$string$21", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$21"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$22", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"m"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$22"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "adjective$string$15", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$15"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$20", "symbols": [{"literal":"a"}, {"literal":"g"}, {"literal":"r"}, {"literal":"e"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$20"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$23", "symbols": [{"literal":"a"}, {"literal":"i"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$23"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$24", "symbols": [{"literal":"a"}, {"literal":"i"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$24"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "adjective$string$16", "symbols": [{"literal":"a"}, {"literal":"l"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$16"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "adverb$string$12", "symbols": [{"literal":"a"}, {"literal":"l"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$12"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "preposition$string$15", "symbols": [{"literal":"a"}, {"literal":"l"}, {"literal":"o"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "preposition", "symbols": ["preposition$string$15"], "postprocess": (data)=>["preposition",id(data)]},
    {"name": "adverb$string$13", "symbols": [{"literal":"a"}, {"literal":"l"}, {"literal":"r"}, {"literal":"e"}, {"literal":"a"}, {"literal":"d"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$13"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "adverb$string$14", "symbols": [{"literal":"a"}, {"literal":"l"}, {"literal":"w"}, {"literal":"a"}, {"literal":"y"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$14"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "verb$string$21", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$21"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$25", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$25"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$22", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$22"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$23", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$23"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$24", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$24"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$26", "symbols": [{"literal":"a"}, {"literal":"m"}, {"literal":"o"}, {"literal":"u"}, {"literal":"n"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$26"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$25", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$25"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$27", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$27"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$26", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$26"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$17", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":"r"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$17"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$27", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$27"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$18", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$18"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$28", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$28"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adverb$string$15", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"r"}, {"literal":"i"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$15"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "adjective$string$19", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"g"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$19"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "quantifier$string$18", "symbols": [{"literal":"a"}, {"literal":"n"}, {"literal":"o"}, {"literal":"t"}, {"literal":"h"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "quantifier", "symbols": ["quantifier$string$18"], "postprocess": (data)=>["quantifier",id(data)]},
    {"name": "adjective$string$20", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$20"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "adverb$string$16", "symbols": [{"literal":"b"}, {"literal":"a"}, {"literal":"d"}, {"literal":"l"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$16"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "verb$string$29", "symbols": [{"literal":"d"}, {"literal":"i"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$29"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$30", "symbols": [{"literal":"d"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$30"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$28", "symbols": [{"literal":"d"}, {"literal":"o"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$28"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$29", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$29"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$30", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$30"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$31", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$31"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$32", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$32"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$31", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$31"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$33", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$33"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$21", "symbols": [{"literal":"d"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$21"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$34", "symbols": [{"literal":"g"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$34"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$35", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$35"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$32", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$32"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$36", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$36"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$22", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$22"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$37", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$37"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$33", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$33"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "adjective$string$23", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$23"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$38", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$38"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$34", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"f"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$34"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$39", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$39"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$40", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$40"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$24", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$24"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "noun$string$35", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$35"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$41", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"v"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$41"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$42", "symbols": [{"literal":"g"}, {"literal":"i"}, {"literal":"v"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$42"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$25", "symbols": [{"literal":"g"}, {"literal":"o"}, {"literal":"o"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$25"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$43", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$43"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$44", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$44"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "verb$string$45", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$45"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$36", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$36"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$46", "symbols": [{"literal":"h"}, {"literal":"a"}, {"literal":"v"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$46"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$37", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$37"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$47", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$47"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$26", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"b"}, {"literal":"l"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$26"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$48", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$48"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "adjective$string$27", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$27"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "noun$string$38", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$38"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$39", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$39"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "verb$string$49", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$49"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$40", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$40"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "adjective$string$28", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adjective", "symbols": ["adjective$string$28"], "postprocess": (data)=>["adjective",id(data)]},
    {"name": "verb$string$50", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "verb", "symbols": ["verb$string$50"], "postprocess": (data)=>["verb",id(data)]},
    {"name": "noun$string$41", "symbols": [{"literal":"t"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$41"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$42", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$42"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "noun$string$43", "symbols": [{"literal":"t"}, {"literal":"h"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "noun", "symbols": ["noun$string$43"], "postprocess": (data)=>["noun",id(data)]},
    {"name": "adverb$string$17", "symbols": [{"literal":"v"}, {"literal":"e"}, {"literal":"r"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$17"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "adverb$string$18", "symbols": [{"literal":"w"}, {"literal":"e"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "adverb", "symbols": ["adverb$string$18"], "postprocess": (data)=>["adverb",id(data)]},
    {"name": "exclamation$string$1", "symbols": [{"literal":"w"}, {"literal":"o"}, {"literal":"w"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "exclamation", "symbols": ["exclamation$string$1"], "postprocess": (data)=>["exclamation",id(data)]},
    {"name": "text", "symbols": ["sentence"], "postprocess": (data) => ["text", id(data)]},
    {"name": "sentence", "symbols": ["statement"], "postprocess": (data) => ["sentence", id(data)]},
    {"name": "sentence", "symbols": ["question"], "postprocess": (data) => ["sentence", id(data)]},
    {"name": "sentence", "symbols": ["command"], "postprocess": (data) => ["sentence", id(data)]},
    {"name": "sentence", "symbols": ["exclamatory"], "postprocess": (data) => ["sentence", id(data)]},
    {"name": "statement", "symbols": ["head", "_", "tail2"], "postprocess": (data) => ["statement", clean(data)]},
    {"name": "statement", "symbols": ["statement", "_", "coordinating_conjunction", "_", "statement"], "postprocess": (data) => ["statement", clean(data)]},
    {"name": "question", "symbols": ["copula_truth_question"], "postprocess": (data) => ["question", id(data)]},
    {"name": "question", "symbols": ["verb_truth_question"], "postprocess": (data) => ["question", id(data)]},
    {"name": "question", "symbols": ["copula_content_question"], "postprocess": (data) => ["question", id(data)]},
    {"name": "question", "symbols": ["verb_content_question"], "postprocess": (data) => ["question", id(data)]},
    {"name": "copula_truth_question", "symbols": ["CTQ_base"], "postprocess": (data) => ["copula truth question", id(data)]},
    {"name": "copula_truth_question", "symbols": ["CTQ_base", "_", "copula_arguments"], "postprocess": (data) => ["copula truth question", clean(data)]},
    {"name": "verb_truth_question", "symbols": ["noun2"], "postprocess": (data) => ["verb truth question", id(data)]},
    {"name": "verb_truth_question", "symbols": ["DO", "_", "noun2"], "postprocess": (data) => ["verb truth question", clean(data)]},
    {"name": "verb_truth_question", "symbols": ["VTQ_base"], "postprocess": (data) => ["verb truth question", id(data)]},
    {"name": "verb_truth_question", "symbols": ["VTQ_base", "_", "arguments"], "postprocess": (data) => ["verb truth question", clean(data)]},
    {"name": "copula_content_question", "symbols": ["interrogative"], "postprocess": (data) => ["copula content question", id(data)]},
    {"name": "copula_content_question", "symbols": ["CCQ_base"], "postprocess": (data) => ["copula content question", id(data)]},
    {"name": "copula_content_question", "symbols": ["CCQ_base", "_", "copula_arguments"], "postprocess": (data) => ["copula content question", clean(data)]},
    {"name": "verb_content_question", "symbols": ["interrogative"], "postprocess": (data) => ["verb content question", id(data)]},
    {"name": "verb_content_question", "symbols": ["VCQ_base"], "postprocess": (data) => ["verb content question", id(data)]},
    {"name": "verb_content_question", "symbols": ["VCQ_base", "_", "arguments"], "postprocess": (data) => ["verb content question", clean(data)]},
    {"name": "CTQ_base", "symbols": ["copula2", "_", "noun2"], "postprocess": (data) => ["CTQ base", clean(data)]},
    {"name": "CTQ_base", "symbols": ["perfective", "_", "noun2", "_", "copula1"], "postprocess": (data) => ["CTQ base", clean(data)]},
    {"name": "CTQ_base", "symbols": ["aux1", "_", "noun2", "_", "copula1"], "postprocess": (data) => ["CTQ base", clean(data)]},
    {"name": "VTQ_base", "symbols": ["DO", "_", "noun2", "_", "verb2"], "postprocess": (data) => ["VTQ base", clean(data)]},
    {"name": "VTQ_base", "symbols": ["perfective", "_", "noun2", "_", "verb2"], "postprocess": (data) => ["VTQ base", clean(data)]},
    {"name": "VTQ_base", "symbols": ["aux1", "_", "noun2", "_", "verb2"], "postprocess": (data) => ["VTQ base", clean(data)]},
    {"name": "CCQ_base", "symbols": ["interrogative", "_", "copula2"], "postprocess": (data) => ["CCQ base", clean(data)]},
    {"name": "VCQ_base", "symbols": ["interrogative", "_", "DO", "_", "noun2", "_", "verb2"], "postprocess": (data) => ["VCQ base", clean(data)]},
    {"name": "VCQ_base", "symbols": ["interrogative", "_", "perfective", "_", "noun2", "_", "verb2"], "postprocess": (data) => ["VCQ base", clean(data)]},
    {"name": "VCQ_base", "symbols": ["interrogative", "_", "aux1", "_", "noun2", "_", "verb2"], "postprocess": (data) => ["VCQ base", clean(data)]},
    {"name": "command", "symbols": ["tail2"], "postprocess": (data) => ["command", clean(data)]},
    {"name": "exclamatory", "symbols": ["exclamation"], "postprocess": (data) => ["exclamatory", clean(data)]},
    {"name": "head", "symbols": ["noun2"], "postprocess": (data) => ["head", id(data)]},
    {"name": "head", "symbols": ["head", "_", "coordinating_conjunction", "_", "head"], "postprocess": (data) => ["head", clean(data)]},
    {"name": "tail2", "symbols": ["tail1"], "postprocess": (data) => ["tail 2", id(data)]},
    {"name": "tail2", "symbols": ["tail1", "_", "end_phrases"], "postprocess": (data) => ["tail 2", clean(data)]},
    {"name": "tail1", "symbols": ["aux1"], "postprocess": (data) => ["tail 1", id(data)]},
    {"name": "tail1", "symbols": ["verb2"], "postprocess": (data) => ["tail 1", id(data)]},
    {"name": "tail1", "symbols": ["verb2", "_", "arguments"], "postprocess": (data) => ["tail 1", clean(data)]},
    {"name": "tail1", "symbols": ["copula1"], "postprocess": (data) => ["tail 1", id(data)]},
    {"name": "tail1", "symbols": ["copula1", "_", "copula_arguments"], "postprocess": (data) => ["tail 1", clean(data)]},
    {"name": "tail1", "symbols": ["tail2", "_", "coordinating_conjunction", "_", "tail2"], "postprocess": (data) => ["tail 1", clean(data)]},
    {"name": "copula_arguments", "symbols": ["adjective1"], "postprocess": (data) => ["copula arguments", id(data)]},
    {"name": "copula_arguments", "symbols": ["adjectival_AS_phrase"], "postprocess": (data) => ["copula arguments", id(data)]},
    {"name": "copula_arguments", "symbols": ["noun2"], "postprocess": (data) => ["copula arguments", id(data)]},
    {"name": "copula_arguments", "symbols": ["preposition1"], "postprocess": (data) => ["copula arguments", id(data)]},
    {"name": "arguments", "symbols": ["noun2"], "postprocess": (data) => ["arguments", id(data)]},
    {"name": "arguments", "symbols": ["noun2", "_", "noun2"], "postprocess": (data) => ["arguments", clean(data)]},
    {"name": "arguments", "symbols": ["noun2", "_", "noun2", "_", "noun2"], "postprocess": (data) => ["arguments", clean(data)]},
    {"name": "end_phrases", "symbols": ["end_phrase"], "postprocess": (data) => ["end phrases", id(data)]},
    {"name": "end_phrases", "symbols": ["end_phrase", "_", "end_phrases"], "postprocess": (data) => ["end phrases", clean(data)]},
    {"name": "end_phrase", "symbols": ["adverb1"], "postprocess": (data) => ["end phrase", id(data)]},
    {"name": "end_phrase", "symbols": ["preposition1"], "postprocess": (data) => ["end phrase", id(data)]},
    {"name": "property_subclause", "symbols": ["statement"], "postprocess": (data) => ["property subclause", id(data)]},
    {"name": "property_subclause", "symbols": ["tail2"], "postprocess": (data) => ["property subclause", id(data)]},
    {"name": "property_subclause", "symbols": ["subordinating_conjunction", "_", "statement"], "postprocess": (data) => ["property subclause", clean(data)]},
    {"name": "property_subclause", "symbols": ["subordinating_conjunction", "_", "tail2"], "postprocess": (data) => ["property subclause", clean(data)]},
    {"name": "property_subclause", "symbols": ["interrogative", "_", "statement"], "postprocess": (data) => ["property subclause", clean(data)]},
    {"name": "property_subclause", "symbols": ["interrogative", "_", "tail2"], "postprocess": (data) => ["property subclause", clean(data)]},
    {"name": "property_subclause", "symbols": ["property_subclause", "_", "coordinating_conjunction", "_", "property_subclause"], "postprocess": (data) => ["property subclause", clean(data)]},
    {"name": "nominal_subclause", "symbols": ["tail2"], "postprocess": (data) => ["nominal subclause", id(data)]},
    {"name": "nominal_subclause", "symbols": ["subordinating_conjunction", "_", "statement"], "postprocess": (data) => ["nominal subclause", clean(data)]},
    {"name": "nominal_subclause", "symbols": ["subordinating_conjunction", "_", "tail2"], "postprocess": (data) => ["nominal subclause", clean(data)]},
    {"name": "nominal_subclause", "symbols": ["interrogative", "_", "statement"], "postprocess": (data) => ["nominal subclause", clean(data)]},
    {"name": "nominal_subclause", "symbols": ["interrogative", "_", "tail2"], "postprocess": (data) => ["nominal subclause", clean(data)]},
    {"name": "adverbial_subclause", "symbols": ["tail2"], "postprocess": (data) => ["adverbial subclause", id(data)]},
    {"name": "adjectival_AS_phrase", "symbols": ["AS", "_", "adjective1", "_", "AS", "_", "noun2"], "postprocess": (data) => ["AS phrase", clean(data)]},
    {"name": "noun2", "symbols": ["pronoun"], "postprocess": (data) => ["noun 2", id(data)]},
    {"name": "noun2", "symbols": ["possessive"], "postprocess": (data) => ["noun 2", id(data)]},
    {"name": "noun2", "symbols": ["noun1"], "postprocess": (data) => ["noun 2", id(data)]},
    {"name": "noun2", "symbols": ["noun1", "_", "preposition1"], "postprocess": (data) => ["noun 2", clean(data)]},
    {"name": "noun2", "symbols": ["noun1", "_", "property_subclause"], "postprocess": (data) => ["noun 2", clean(data)]},
    {"name": "noun2", "symbols": ["noun2", "_", "coordinating_conjunction", "_", "noun2"], "postprocess": (data) => ["noun 2", clean(data)]},
    {"name": "noun1", "symbols": ["noun"], "postprocess": (data) => ["noun 1", id(data)]},
    {"name": "noun1", "symbols": ["nominal_subclause"], "postprocess": (data) => ["noun 1", id(data)]},
    {"name": "noun1", "symbols": ["adjective1", "_", "noun"], "postprocess": (data) => ["noun 1", clean(data)]},
    {"name": "noun1", "symbols": ["determiner", "_", "noun"], "postprocess": (data) => ["noun 1", clean(data)]},
    {"name": "noun1", "symbols": ["determiner", "_", "adjective1", "_", "noun"], "postprocess": (data) => ["noun 1", clean(data)]},
    {"name": "verb1", "symbols": ["verb"], "postprocess": (data) => ["verb 1", id(data)]},
    {"name": "verb1", "symbols": ["adverb1", "_", "verb"], "postprocess": (data) => ["verb 1", clean(data)]},
    {"name": "verb2", "symbols": ["verb1"], "postprocess": (data) => ["verb 2", id(data)]},
    {"name": "verb2", "symbols": ["adverb1", "_", "verb1"], "postprocess": (data) => ["verb 2", clean(data)]},
    {"name": "verb2", "symbols": ["aux1", "_", "verb1"], "postprocess": (data) => ["verb 2", clean(data)]},
    {"name": "verb2", "symbols": ["adverb1", "_", "aux1", "_", "verb1"], "postprocess": (data) => ["verb 2", clean(data)]},
    {"name": "verb2", "symbols": ["perfective", "_", "verb1"], "postprocess": (data) => ["verb 2", clean(data)]},
    {"name": "verb2", "symbols": ["adverb1", "_", "perfective", "_", "verb1"], "postprocess": (data) => ["verb 2", clean(data)]},
    {"name": "verb2", "symbols": ["copula2", "_", "verb1"], "postprocess": (data) => ["verb 2", clean(data)]},
    {"name": "verb2", "symbols": ["adverb1", "_", "copula2", "_", "verb1"], "postprocess": (data) => ["verb 2", clean(data)]},
    {"name": "verb2", "symbols": ["verb1", "_", "coordinating_conjunction", "_", "verb1"], "postprocess": (data) => ["verb 2", clean(data)]},
    {"name": "aux1", "symbols": ["aux_verb"], "postprocess": (data) => ["aux. phrase", id(data)]},
    {"name": "aux1", "symbols": ["aux_verb", "_", "NOT"], "postprocess": (data) => ["aux. phrase", clean(data)]},
    {"name": "copula2", "symbols": ["copula1"], "postprocess": (data) => ["copula 2", id(data)]},
    {"name": "copula2", "symbols": ["adverb1", "_", "copula1"], "postprocess": (data) => ["copula 2", clean(data)]},
    {"name": "copula2", "symbols": ["copula1", "_", "NOT"], "postprocess": (data) => ["copula 2", clean(data)]},
    {"name": "copula2", "symbols": ["adverb1", "_", "copula1", "_", "NOT"], "postprocess": (data) => ["copula 2", clean(data)]},
    {"name": "copula2", "symbols": ["aux1", "_", "copula1"], "postprocess": (data) => ["copula 2", clean(data)]},
    {"name": "copula2", "symbols": ["adverb1", "_", "aux1", "_", "copula1"], "postprocess": (data) => ["copula 2", clean(data)]},
    {"name": "copula2", "symbols": ["perfective", "_", "copula1"], "postprocess": (data) => ["copula 2", clean(data)]},
    {"name": "copula2", "symbols": ["aux1", "_", "perfective", "_", "copula1"], "postprocess": (data) => ["copula 2", clean(data)]},
    {"name": "copula2", "symbols": ["perfective", "_", "NOT", "_", "copula1"], "postprocess": (data) => ["copula 2", clean(data)]},
    {"name": "copula2", "symbols": ["aux1", "_", "perfective", "_", "NOT", "_", "copula1"], "postprocess": (data) => ["copula 2", clean(data)]},
    {"name": "copula2", "symbols": ["adverb1", "_", "perfective", "_", "copula1"], "postprocess": (data) => ["copula 2", clean(data)]},
    {"name": "copula2", "symbols": ["aux1", "_", "adverb1", "_", "perfective", "_", "copula1"], "postprocess": (data) => ["copula 2", clean(data)]},
    {"name": "copula2", "symbols": ["adverb1", "_", "perfective", "_", "NOT", "_", "copula1"], "postprocess": (data) => ["copula 2", clean(data)]},
    {"name": "copula2", "symbols": ["aux1", "_", "adverb1", "_", "perfective", "_", "NOT", "_", "copula1"], "postprocess": (data) => ["copula 2", clean(data)]},
    {"name": "copula1", "symbols": ["copula"], "postprocess": (data) => ["copula 1", id(data)]},
    {"name": "copula1", "symbols": ["adverb1", "_", "copula"], "postprocess": (data) => ["copula 1", clean(data)]},
    {"name": "adjective1", "symbols": ["adjective"], "postprocess": (data) => ["adjective 1", id(data)]},
    {"name": "adjective1", "symbols": ["adverb1", "_", "adjective"], "postprocess": (data) => ["adjective 1", clean(data)]},
    {"name": "adjective1", "symbols": ["adjective1", "_", "adjective1"], "postprocess": (data) => ["adjective 1", clean(data)]},
    {"name": "adjective1", "symbols": ["adjective1", "_", "coordinating_conjunction", "_", "adjective1"], "postprocess": (data) => ["adjective 1", clean(data)]},
    {"name": "adverb1", "symbols": ["adverb"], "postprocess": (data) => ["adverb 1", id(data)]},
    {"name": "adverb1", "symbols": ["adverb1", "_", "adverb"], "postprocess": (data) => ["adverb 1", clean(data)]},
    {"name": "preposition1+", "symbols": ["preposition1"], "postprocess": (data) => ["preposition 1+", id(data)]},
    {"name": "preposition1+", "symbols": ["preposition1", "_", "preposition1+"], "postprocess": (data) => ["preposition 1+", clean(data)]},
    {"name": "preposition1", "symbols": ["preposition"], "postprocess": (data) => ["preposition 1", id(data)]},
    {"name": "preposition1", "symbols": ["postposition"], "postprocess": (data) => ["preposition 1", id(data)]},
    {"name": "preposition1", "symbols": ["preposition", "_", "noun2"], "postprocess": (data) => ["preposition 1", clean(data)]},
    {"name": "preposition1", "symbols": ["noun2", "_", "postposition"], "postprocess": (data) => ["preposition 1", clean(data)]},
    {"name": "preposition1", "symbols": ["preposition1", "_", "coordinating_conjunction", "_", "preposition1"], "postprocess": (data) => ["preposition 1", clean(data)]},
    {"name": "determiner", "symbols": ["quantifier1"], "postprocess": (data) => ["determiner", id(data)]},
    {"name": "determiner", "symbols": ["quantifier1", "_", "determiner"], "postprocess": (data) => ["determiner", clean(data)]},
    {"name": "determiner", "symbols": ["determiner", "_", "quantifier1"], "postprocess": (data) => ["determiner", clean(data)]},
    {"name": "noun", "symbols": ["quantifier"], "postprocess": (data) => ["noun", id(data)]},
    {"name": "quantifier1", "symbols": ["quantifier"], "postprocess": (data) => ["quantifier 1", id(data)]},
    {"name": "quantifier1", "symbols": ["quantifier", "_", "OF"], "postprocess": (data) => ["quantifier 1", clean(data)]},
    {"name": "_", "symbols": [{"literal":" "}], "postprocess": id}
]
  , ParserStart: "text"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
